parameters:
    pim_catalog.entity.product_value.color.class: Acme\Bundle\AppBundle\Model\ColorProductValue
    pim_catalog.entity.product_value.fabrics.class: Acme\Bundle\AppBundle\Model\FabricsProductValue
    acme_app.entity.color.class:            Acme\Bundle\AppBundle\Entity\Color
    acme_app.entity.fabric.class:           Acme\Bundle\AppBundle\Entity\Fabric
