parameters:
    pim_serializer.normalizer.mongodb.product.class:       Pim\Bundle\CatalogBundle\MongoDB\Normalizer\Document\ProductNormalizer
    pim_serializer.normalizer.mongodb.product_value.class: Pim\Bundle\CatalogBundle\MongoDB\Normalizer\Document\ProductValueNormalizer
    pim_serializer.normalizer.mongodb.metric.class:        Pim\Bundle\CatalogBundle\MongoDB\Normalizer\Document\MetricNormalizer
    pim_serializer.normalizer.mongodb.price.class:         Pim\Bundle\CatalogBundle\MongoDB\Normalizer\Document\ProductPriceNormalizer
    pim_serializer.normalizer.mongodb.datetime.class:      Pim\Bundle\CatalogBundle\MongoDB\Normalizer\Document\DateTimeNormalizer
    pim_serializer.normalizer.mongodb.association.class:   Pim\Bundle\CatalogBundle\MongoDB\Normalizer\Document\AssociationNormalizer
    pim_serializer.normalizer.mongodb.version.class:       Pim\Bundle\CatalogBundle\MongoDB\Normalizer\Document\VersionNormalizer
    pim_serializer.normalizer.mongodb.generic.class:       Pim\Bundle\CatalogBundle\MongoDB\Normalizer\Document\GenericNormalizer

services:
    # Object to MongoDB document normalizers
    pim_serializer.normalizer.mongodb.product:
        class: %pim_serializer.normalizer.mongodb.product.class%
        arguments:
            - '@pim_catalog.mongodb.mongo_objects_factory'
        tags:
            - { name: pim_serializer.normalizer, priority: 100 }

    pim_serializer.normalizer.mongodb.product_value:
        class: %pim_serializer.normalizer.mongodb.product_value.class%
        arguments:
            - '@pim_catalog.mongodb.mongo_objects_factory'
            - '@pim_catalog.doctrine.smart_manager_registry'
        tags:
            - { name: pim_serializer.normalizer, priority: 100 }

    pim_serializer.normalizer.mongodb.metric:
        class: %pim_serializer.normalizer.mongodb.metric.class%
        arguments:
            - '@pim_catalog.mongodb.mongo_objects_factory'
            - '@akeneo_measure.measure_converter'
            - '@akeneo_measure.manager'
        tags:
            - { name: pim_serializer.normalizer, priority: 100 }

    pim_serializer.normalizer.mongodb.price:
        class: %pim_serializer.normalizer.mongodb.price.class%
        arguments:
            - '@pim_catalog.mongodb.mongo_objects_factory'
        tags:
            - { name: pim_serializer.normalizer, priority: 100 }

    pim_serializer.normalizer.mongodb.datetime:
        class: %pim_serializer.normalizer.mongodb.datetime.class%
        arguments:
            - '@pim_catalog.mongodb.mongo_objects_factory'
        tags:
            - { name: pim_serializer.normalizer, priority: 100 }

    pim_serializer.normalizer.mongodb.association:
        class: %pim_serializer.normalizer.mongodb.association.class%
        arguments:
            - '@pim_catalog.mongodb.mongo_objects_factory'
        tags:
            - { name: pim_serializer.normalizer, priority: 100 }

    pim_serializer.normalizer.mongodb.version:
        class: %pim_serializer.normalizer.mongodb.version.class%
        arguments:
            - '@pim_catalog.mongodb.mongo_objects_factory'
        tags:
            - { name: pim_serializer.normalizer, priority: 100 }

    pim_serializer.normalizer.mongodb.generic:
        class: %pim_serializer.normalizer.mongodb.generic.class%
        arguments:
            - '@pim_catalog.mongodb.mongo_objects_factory'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
