Pim\Bundle\BaseConnectorBundle\Writer\File\CsvWriter:
    properties:
        delimiter:
            - NotBlank: ~
            - Choice:
                choices: [",", ";", "|"]
                message: The value must be one of , or ; or |
        enclosure:
            - NotBlank: ~
            - Choice:
                choices: ['"', "'"]
                message: The value must be one of " or '
