parameters:
    pim_import_export.transformer.guesser.chained.class:            Pim\Bundle\ImportExportBundle\Transformer\Guesser\ChainedGuesser
    pim_import_export.transformer.guesser.type.class:               Pim\Bundle\ImportExportBundle\Transformer\Guesser\TypeGuesser
    pim_import_export.transformer.guesser.relation.class:           Pim\Bundle\ImportExportBundle\Transformer\Guesser\RelationGuesser
    pim_import_export.transformer.guesser.translation.class:        Pim\Bundle\ImportExportBundle\Transformer\Guesser\TranslationGuesser
    pim_import_export.transformer.guesser.nested_translation.class: Pim\Bundle\ImportExportBundle\Transformer\Guesser\NestedTranslationGuesser
    pim_import_export.transformer.guesser.default.class:            Pim\Bundle\ImportExportBundle\Transformer\Guesser\DefaultGuesser
    pim_import_export.transformer.guesser.regexp.class:             Pim\Bundle\ImportExportBundle\Transformer\Guesser\RegexpGuesser
    pim_import_export.transformer.guesser.attribute.class:          Pim\Bundle\ImportExportBundle\Transformer\Guesser\AttributeGuesser
    pim_import_export.transformer.guesser.attribute_option.class:   Pim\Bundle\ImportExportBundle\Transformer\Guesser\AttributeOptionGuesser

services:
    pim_import_export.transformer.guesser:
        class: %pim_import_export.transformer.guesser.chained.class%

    pim_import_export.transformer.guesser.default:
        class: %pim_import_export.transformer.guesser.default.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.default'
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 0 }

    pim_import_export.transformer.guesser.attribute_option_value:
        class: %pim_import_export.transformer.guesser.regexp.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.translation'
            - %pim_catalog.entity.attribute_option.class%
            - ['/^label-/']
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 40 }

    pim_import_export.transformer.guesser.translation:
        class: %pim_import_export.transformer.guesser.translation.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.translation'
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 40 }

    pim_import_export.transformer.guesser.nested_translation:
        class: %pim_import_export.transformer.guesser.nested_translation.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.nested_translation'
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 40 }

    pim_import_export.transformer.guesser.nested_attribute_option_value:
        class: %pim_import_export.transformer.guesser.regexp.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.nested_translation'
            - %pim_catalog.entity.attribute_option.class%
            - ['/^labels$/']
            - { propertyPath: label }
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 40 }

    pim_import_export.transformer.guesser.media:
        class: %pim_import_export.transformer.guesser.attribute.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.media'
            - %pim_catalog.entity.product_value.class%
            - media
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 40 }

    pim_import_export.transformer.guesser.prices:
        class: %pim_import_export.transformer.guesser.attribute.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.prices'
            - %pim_catalog.entity.product_value.class%
            - prices
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 40 }

    pim_import_export.transformer.guesser.metric:
        class: %pim_import_export.transformer.guesser.attribute.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.metric'
            - %pim_catalog.entity.product_value.class%
            - metric
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 40 }

    pim_import_export.transformer.guesser.date:
        class: %pim_import_export.transformer.guesser.type.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.date'
            - date
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 50 }

    pim_import_export.transformer.guesser.datetime:
        class: %pim_import_export.transformer.guesser.type.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.date'
            - datetime
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 50 }


    pim_import_export.transformer.guesser.boolean:
        class: %pim_import_export.transformer.guesser.type.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.boolean'
            - boolean
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 50 }


    pim_import_export.transformer.guesser.relation:
        class: %pim_import_export.transformer.guesser.relation.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.relation'
            - '@doctrine'
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 50 }

    pim_import_export.transformer.guesser.skip_attribute_type:
        class: %pim_import_export.transformer.guesser.regexp.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.skip'
            - %pim_catalog.entity.attribute.class%
            - ['/^type$/']
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 50 }

    pim_import_export.transformer.guesser.attribute_options:
        class: %pim_import_export.transformer.guesser.attribute_option.class%
        public: false
        parent: pim_import_export.transformer.guesser.relation
        arguments:
            - %pim_catalog.entity.product_value.class%
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 200 }

    pim_import_export.transformer.guesser.category_product:
        class: %pim_import_export.transformer.guesser.regexp.class%
        public: false
        arguments:
            - '@pim_import_export.transformer.property.relation'
            - %pim_catalog.entity.category.class%
            - ['/^products/']
            - { class: %pim_catalog.entity.product.class%, multiple: true }
        tags:
            - { name: pim_import_export.transformer.guesser, priority: 40 }
