oro_menu_config:
    items:
        pim_ie_import:
            label: pim_menu.item.import_profile
            route: pim_importexport_import_profile_index
            aclResourceId: pim_importexport_import_profile_index
        pim_ie_export:
            label: pim_menu.item.export_profile
            route: pim_importexport_export_profile_index
            aclResourceId: pim_importexport_export_profile_index
        pim_report_import:
            label: pim_menu.item.import_history
            route: pim_importexport_import_execution_index
            aclResourceId: pim_importexport_import_execution_index
        pim_report_export:
            label: pim_menu.item.export_history
            route: pim_importexport_export_execution_index
            aclResourceId: pim_importexport_export_execution_index

    tree:
        application_menu:
            children:
                pim_import_tab:
                    children:
                        pim_ie_import: ~
                        pim_report_import: ~
                pim_export_tab:
                    children:
                        pim_ie_export: ~
                        pim_report_export: ~

oro_titles:
    pim_importexport_export_profile_index:   pim_title.export_profile.index
    pim_importexport_export_profile_edit:    pim_title.export_profile.edit
    pim_importexport_export_profile_show:    pim_title.export_profile.show
    
    pim_importexport_import_profile_index:   pim_title.import_profile.index
    pim_importexport_import_profile_edit:    pim_title.import_profile.edit
    pim_importexport_import_profile_show:    pim_title.import_profile.show
