parameters:
    pim_import_export.twig.normalize_configuration_extension.class:  Pim\Bundle\ImportExportBundle\Twig\NormalizeConfigurationExtension
    pim_import_export.validator.constraints.channel_validator.class: Pim\Bundle\ImportExportBundle\Validator\Constraints\ChannelValidator
    pim_import_export.validator.import.class:                        Pim\Bundle\ImportExportBundle\Validator\Import\ImportValidator
    pim_import_export.validator.product_import.class:                Pim\Bundle\ImportExportBundle\Validator\Import\ProductImportValidator
    pim_import_export.validator.skip_import.class:                   Pim\Bundle\ImportExportBundle\Validator\Import\SkipImportValidator

services:
    pim_import_export.twig.normalize_configuration_extension:
        class: %pim_import_export.twig.normalize_configuration_extension.class%
        tags:
            - { name: twig.extension }

    pim_import_export.validator.constraints.channel_validator:
        class: %pim_import_export.validator.constraints.channel_validator.class%
        arguments:
            - '@pim_catalog.manager.channel'
        tags:
            - { name: validator.constraint_validator, alias: channel_validator }

    pim_import_export.validator.import:
        class: %pim_import_export.validator.import.class%
        arguments:
            - '@validator'

    pim_import_export.validator.product_import:
        class: %pim_import_export.validator.product_import.class%
        parent: pim_import_export.validator.import
        arguments:
            - '@pim_flexibleentity.validator.attribute_constraint_guesser'

    pim_import_export.validator.skip_import:
        class: %pim_import_export.validator.skip_import.class%

    pim_import_export.validator.job_instance:
        class: Pim\Bundle\ImportExportBundle\Validator\Constraints\JobInstanceValidator
        arguments:
            - '@oro_batch.connectors'
        tags:
            - { name: validator.constraint_validator, alias: pim_job_instance_validator }
