Pim\Bundle\CatalogBundle\Entity\SequentialEdit:
    type: entity
    table: pim_catalog_sequential_edit
    repositoryClass: Pim\Bundle\CatalogBundle\Entity\Repository\SequentialEditRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        productSet:
            type: array
    oneToOne:
        user:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            joinColumn:
                name: user_id
                referencedColumnName: id
