datagrid:
    groups-grid:
        options:
            entityHint: group
        source:
            acl_resource: pim_user_group_index
            type: orm
            query:
                select:
                    - g.id
                    - g.name
                from:
                    - { table: OroUserBundle:Group, alias: g }
                where:
                    and:
                        - g.name <> '%oro_user.entity.class%::GROUP_DEFAULT'
        columns:
            name:
                label: oro.user.grid.groups.columns.name

        properties:
            id: ~
            update_link:
                type: url
                route: oro_user_group_update
                params:
                    - id

            delete_link:
                type: url
                route: oro_user_group_delete
                params:
                    - id

        actions:
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  pim_user_group_edit
                rowAction:     true
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  pim_user_group_remove

        sorters:
            columns:
                name:
                    data_name: g.name
            default:
                name: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'

        filters:
            columns:
                name:
                    type: string
                    data_name: g.name

    roles-grid:
        options:
            entityHint: role
        source:
            acl_resource: pim_user_role_index
            type: orm
            query:
                select:
                    - r.id
                    - r.role
                    - r.label
                from:
                    - { table: OroUserBundle:Role, alias: r }
                where:
                    and:
                        - r.role <> '%oro_user.entity.class%::ROLE_ANONYMOUS'
        columns:
            label:
                label: oro.user.grid.roles.columns.label

        properties:
            id: ~
            update_link:
                type: url
                route: oro_user_role_update
                params:
                    - id

            delete_link:
                type: url
                route: oro_user_role_delete
                params:
                    - id

        actions:
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  pim_user_role_edit
                rowAction:     true
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  pim_user_role_remove

        sorters:
            columns:
                label:
                    data_name: r.label
            default:
                label: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'

        filters:
            columns:
                label:
                    type: string
                    data_name: r.label

    user-relation-grid:
        source:
            type: orm
            query:
                select:
                    - u.id
                    - u.username
                    - u.email
                    - u.firstName
                    - u.lastName
                from:
                    - { table: PimUserBundle:User, alias: u }

        columns: []

        properties:
            id: ~

        sorters:
            columns:
                username:
                    data_name: u.username
                email:
                    data_name: u.email
                firstName:
                    data_name: u.firstName
                lastName:
                    data_name: u.lastName
            default:
                id: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'

        filters: []
