parameters:
    akeneo_measure.measures_config: ~

services:
    akeneo_measure.measure_converter:
        class: Akeneo\Bundle\MeasureBundle\Convert\MeasureConverter
        arguments: [%akeneo_measure.measures_config%]

    akeneo_measure.manager:
        class: Oro\Bundle\MeasureBundle\Manager\MeasureManager
