language: php
php:
    - "5.4"
    - "5.5"
    - "hhvm"

matrix:
    allow_failures:
        - php: "5.5"
        - php: hhvm

before_script:
    - composer self-update --no-interaction
    - composer require  --no-update doctrine/mongodb-odm-bundle 3.0.*@dev
    - composer update --prefer-source --no-scripts --no-interaction

script:
    - phpunit -c app/phpunit.travis.xml --testsuite PIM_Unit_Test
    - ./phpspec-fix
