parameters:
    pim_transform.builder.field_name.class: Pim\Bundle\TransformBundle\Builder\FieldNameBuilder

services:
    # deprecated will be dropped in 1.5
    pim_transform.builder.field_name:
        class: %pim_transform.builder.field_name.class%
        arguments:
          - '@pim_connector.array_converter.flat.attribute_field_extractor'
          - '@pim_connector.array_converter.flat.association_field_resolver'
