parameters:
    pim_transform.cache.doctrine_cache.class:        Pim\Bundle\TransformBundle\Cache\DoctrineCache
    pim_transform.cache.attribute_cache.class:       Pim\Bundle\TransformBundle\Cache\AttributeCache
    pim_transform.cache.product_cache_clearer.class: Pim\Bundle\TransformBundle\Cache\ProductCacheClearer

services:
    pim_transform.cache.doctrine_cache:
        class: %pim_transform.cache.doctrine_cache.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'

    pim_transform.cache.attribute_cache:
        class: %pim_transform.cache.attribute_cache.class%
        arguments:
            - '@doctrine'
            - %pim_catalog.entity.attribute.class%

    pim_transform.cache.product_cache_clearer:
        class: %pim_transform.cache.product_cache_clearer.class%
        arguments:
            - '@pim_transform.cache.doctrine_cache'
            - '@doctrine'
        calls:
            - [ addNonClearableEntity, [ %pim_catalog.entity.attribute.class% ] ]
            - [ addNonClearableEntity, [ %pim_catalog.entity.category.class% ] ]
