parameters:
    pim_transform.filter.product_value.class:      Pim\Bundle\TransformBundle\Filter\ProductValueFilter
    pim_transform.filter.flat_product_value.class: Pim\Bundle\TransformBundle\Filter\FlatProductValueFilter

services:
    pim_transform.filter.product_value:
        class: %pim_transform.filter.product_value.class%

    pim_transform.filter.flat_product_value:
        class: %pim_transform.filter.flat_product_value.class%

