parameters:
    pim_import_export.repository.product.search.class: Pim\Bundle\ImportExportBundle\Doctrine\MongoDBODM\Repository\ProductSearchableRepository
services:
    pim_import_export.repository.product.search:
        class: '%pim_import_export.repository.product.search.class%'
        arguments:
            - '@pim_catalog.query.product_query_builder_factory'
            - '@pim_catalog.repository.attribute'
