parameters:
    pim_versioning.event_listener.addversion.class:        Pim\Bundle\VersioningBundle\EventSubscriber\AddVersionListener
    pim_versioning.event_listener.adduser.class:           Pim\Bundle\VersioningBundle\EventSubscriber\AddUserListener
    pim_versioning.event_listener.addcontext.class:        Pim\Bundle\VersioningBundle\EventSubscriber\AddContextListener

services:
    pim_versioning.event_listener.addversion:
        class: %pim_versioning.event_listener.addversion.class%
        arguments:
            - '@pim_versioning.manager.version'
            - '@pim_versioning.update_guesser.chained'
            - '@pim_versioning.serializer'
        tags:
            - { name: doctrine.event_subscriber }

    pim_versioning.event_listener.adduser:
        class: %pim_versioning.event_listener.adduser.class%
        arguments:
            - '@pim_versioning.manager.version'
            - '@security.context'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

    pim_versioning.event_listener.addcontext:
        class: %pim_versioning.event_listener.addcontext.class%
        arguments:
            - '@pim_versioning.manager.version'
        tags:
            - { name: kernel.event_subscriber}
