Acme\Bundle\AppBundle\Entity\Car:
    repositoryClass: Pim\Bundle\CatalogBundle\Doctrine\ORM\Repository\ReferenceDataOptionRepository
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        brand:
            type: string
            length: 255
        model:
            type: string
            length: 255
        year:
            type: integer
    lifecycleCallbacks: {  }
