Acme\Bundle\AppBundle\Entity\Moto:
    repositoryClass: Pim\Bundle\ReferenceDataBundle\Doctrine\ORM\Repository\ReferenceDataRepository
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            unique: true
        brand:
            type: string
            length: 255
        model:
            type: string
            length: 255
        year:
            type: integer
    lifecycleCallbacks: {  }
