parameters:
    pim_reference_data.mongodb.normalizer.reference_data.class: Pim\Bundle\ReferenceDataBundle\MongoDB\Normalizer\ReferenceDataNormalizer
    pim_reference_data.doctrine.query.filter.reference_data.class: Pim\Bundle\ReferenceDataBundle\Doctrine\MongoDB\Filter\ReferenceDataFilter

services:
    pim_reference_data.mongodb.normalizer.reference_data:
        class: %pim_reference_data.mongodb.normalizer.reference_data.class%
        public: false
        tags:
            - { name: pim_serializer.normalizer }
