parameters:
    pim_base_connector.factory.job_configuration.class: Pim\Bundle\BaseConnectorBundle\Factory\JobConfigurationFactory

services:
    pim_base_connector.factory.job_configuration:
        class: %pim_base_connector.factory.job_configuration.class%
        arguments:
            - %pim_enrich.entity.mass_edit.job_configuration.class%
