parameters:
    pim_base_connector.launcher.simple_job_launcher.class: Pim\Bundle\BaseConnectorBundle\JobLauncher\SimpleJobLauncher

services:
    pim_base_connector.launcher.simple_job_launcher:
        class: %pim_base_connector.launcher.simple_job_launcher.class%
        arguments:
            - '@akeneo_batch.job_repository'
            - '@pim_enrich.factory.mass_edit.job_configuration'
            - '@doctrine.orm.entity_manager'
            - '%kernel.root_dir%'
            - '%kernel.environment%'
