parameters:
    pim_base_connector.reader.repository.group.class:         Pim\Bundle\BaseConnectorBundle\Reader\Repository\GroupReader
    pim_base_connector.reader.repository.variant_group.class: Pim\Bundle\BaseConnectorBundle\Reader\Repository\VariantGroupReader

    pim_base_connector.reader.cached.class:            Pim\Bundle\BaseConnectorBundle\Reader\CachedReader

services:
#    pim_base_connector.reader.orm.category:
#        class: '%pim_base_connector.reader.orm.category.class%'
#        arguments:
#            - '@pim_catalog.repository.category'

#    pim_base_connector.reader.orm.attribute:
#        class: '%pim_base_connector.reader.orm.entity.class%'
#        arguments:
#            - '@doctrine.orm.default_entity_manager'
#            - '%pim_catalog.entity.attribute.class%'

#    pim_base_connector.reader.orm.attribute_option:
#        class: '%pim_base_connector.reader.orm.attribute_option.class%'
#        arguments:
#            - '@doctrine.orm.default_entity_manager'
#            - '%pim_catalog.entity.attribute_option.class%'

#    pim_base_connector.reader.orm.association_type:
#        class: '%pim_base_connector.reader.orm.entity.class%'
#        arguments:
#            - '@doctrine.orm.default_entity_manager'
#            - '%pim_catalog.entity.association_type.class%'

    pim_base_connector.reader.repository.group:
        class: '%pim_base_connector.reader.repository.group.class%'
        arguments:
            - '@pim_catalog.repository.group'

    pim_base_connector.reader.repository.variant_group:
        class: '%pim_base_connector.reader.repository.variant_group.class%'
        arguments:
            - '@pim_catalog.repository.group'

#    pim_base_connector.reader.orm.family:
#        class: '%pim_base_connector.reader.orm.entity.class%'
#        arguments:
#            - '@doctrine.orm.default_entity_manager'
#            - '%pim_catalog.entity.family.class%'
