# TODO This page is only tested by the test
# features/navigation/navigate_using_hash_navigation.feature:7
# and can not be reached by the UI. Maybe we have to remove it ?
extensions:
    pim-import-execution-index:
        module: pim/form/common/index/index
        config:
            title: pim_enrich.index.import_history.title

    pim-import-execution-index-grid-container:
        module: pim/common/simple-view
        parent: pim-import-execution-index
        targetZone: content
        config:
            template: pim/template/form/index/index

    pim-import-execution-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-import-execution-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    pim-import-execution-index-filters-list:
        module: oro/datafilter/filters-list
        parent: pim-import-execution-index-grid-container
        targetZone: filters

    pim-import-execution-index-filters-manage:
        module: oro/datafilter/filters-button
        parent: pim-import-execution-index-grid-container
        targetZone: filters

    pim-import-execution-index-pagination:
        module: oro/datagrid/pagination-input
        parent: pim-import-execution-index-grid-container
        targetZone: toolbar

    pim-import-execution-index-grid:
        module: pim/form/common/index/grid
        parent: pim-import-execution-index
        position: 1000
        targetZone: content
        config:
            alias: import-execution-grid
            metadata:
                jobType: import
