parameters:
    pim_catalog.validator.constraint_guesser.chained.class:          Pim\Bundle\CatalogBundle\Validator\ChainedAttributeConstraintGuesser
    pim_catalog.validator.constraint_guesser.email.class:            Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\EmailGuesser
    pim_catalog.validator.constraint_guesser.file.class:             Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\FileGuesser
    pim_catalog.validator.constraint_guesser.length.class:           Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\LengthGuesser
    pim_catalog.validator.constraint_guesser.not_blank.class:        Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\NotBlankGuesser
    pim_catalog.validator.constraint_guesser.date.class:             Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\DateGuesser
    pim_catalog.validator.constraint_guesser.numeric.class:          Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\NumericGuesser
    pim_catalog.validator.constraint_guesser.range.class:            Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\RangeGuesser
    pim_catalog.validator.constraint_guesser.regex.class:            Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\RegexGuesser
    pim_catalog.validator.constraint_guesser.not_decimal.class:      Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\NotDecimalGuesser
    pim_catalog.validator.constraint_guesser.url.class:              Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\UrlGuesser
    pim_catalog.validator.constraint_guesser.unique_value.class:     Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\UniqueValueGuesser
    pim_catalog.validator.constraint_guesser.price_collection.class: Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\PriceCollectionGuesser
    pim_catalog.validator.constraint_guesser.metric.class:           Pim\Bundle\CatalogBundle\Validator\ConstraintGuesser\MetricGuesser

services:
    pim_catalog.validator.attribute_constraint_guesser:
        class: %pim_catalog.validator.constraint_guesser.chained.class%
        public: false

    pim.attribute_constraint_guesser.email:
        public: false
        class: %pim_catalog.validator.constraint_guesser.email.class%
        tags:
            - { name: pim.attribute_constraint_guesser }

    pim.attribute_constraint_guesser.file:
        public: false
        class: %pim_catalog.validator.constraint_guesser.file.class%
        tags:
            - { name: pim.attribute_constraint_guesser }

    pim.attribute_constraint_guesser.length:
        public: false
        class: %pim_catalog.validator.constraint_guesser.length.class%
        tags:
            - { name: pim.attribute_constraint_guesser }

    pim.attribute_constraint_guesser.not_blank:
        public: false
        class: %pim_catalog.validator.constraint_guesser.not_blank.class%
        tags:
            - { name: pim.attribute_constraint_guesser }

    pim.attribute_constraint_guesser.date:
        public: false
        class: %pim_catalog.validator.constraint_guesser.date.class%
        tags:
            - { name: pim.attribute_constraint_guesser }

    pim.attribute_constraint_guesser.numeric:
        public: false
        class: %pim_catalog.validator.constraint_guesser.numeric.class%
        tags:
            - { name: pim.attribute_constraint_guesser }

    pim.attribute_constraint_guesser.range:
        public: false
        class: %pim_catalog.validator.constraint_guesser.range.class%
        tags:
            - { name: pim.attribute_constraint_guesser }

    pim.attribute_constraint_guesser.regex:
        public: false
        class: %pim_catalog.validator.constraint_guesser.regex.class%
        tags:
            - { name: pim.attribute_constraint_guesser }

    pim.attribute_constraint_guesser.not_decimal:
        public: false
        class: %pim_catalog.validator.constraint_guesser.not_decimal.class%
        tags:
            - { name: pim.attribute_constraint_guesser }

    pim.attribute_constraint_guesser.url:
        public: false
        class: %pim_catalog.validator.constraint_guesser.url.class%
        tags:
            - { name: pim.attribute_constraint_guesser }

    pim.attribute_constraint_guesser.unique_value:
        public: false
        class: %pim_catalog.validator.constraint_guesser.unique_value.class%
        tags:
            - { name: pim.attribute_constraint_guesser }

    pim.attribute_constraint_guesser.price_collection:
        public: false
        class: %pim_catalog.validator.constraint_guesser.price_collection.class%
        tags:
            - { name: pim.attribute_constraint_guesser }

    pim.attribute_constraint_guesser.metric:
        public: false
        class: %pim_catalog.validator.constraint_guesser.metric.class%
        tags:
            - { name: pim.attribute_constraint_guesser }
