parameters:
    pim_catalog.completeness.checker.registry.class:         Pim\Component\Catalog\Completeness\Checker\CompleteCheckerRegistry
    pim_catalog.completeness.checker.product_value.class:    Pim\Component\Catalog\Completeness\Checker\ProductValueCompleteChecker
    pim_catalog.completeness.checker.attribute.media.class:  Pim\Component\Catalog\Completeness\Checker\Attribute\MediaCompleteChecker
    pim_catalog.completeness.checker.attribute.metric.class: Pim\Component\Catalog\Completeness\Checker\Attribute\MetricCompleteChecker
    pim_catalog.completeness.checker.attribute.price.class:  Pim\Component\Catalog\Completeness\Checker\Attribute\PriceCompleteChecker

services:
    pim_catalog.completeness.checker.registry:
        class: %pim_catalog.completeness.checker.registry.class%

    pim_catalog.completeness.checker.product_value:
        class: %pim_catalog.completeness.checker.product_value.class%
        arguments:
          - '@pim_catalog.completeness.checker.registry'

    pim_catalog.completeness.checker.attribute.media:
        class: %pim_catalog.completeness.checker.attribute.media.class%
        tags:
            - { name: completeness.checker.attribute }

    pim_catalog.completeness.checker.attribute.metric:
        class: %pim_catalog.completeness.checker.attribute.metric.class%
        tags:
            - { name: completeness.checker.attribute }

    pim_catalog.completeness.checker.attribute.price:
        class: %pim_catalog.completeness.checker.attribute.price.class%
        tags:
            - { name: completeness.checker.attribute }
