parameters:
    pim_catalog.comparator.registry.class:          Pim\Component\Catalog\Comparator\ComparatorRegistry
    pim_catalog.comparator.attribute.media.class:   Pim\Component\Catalog\Comparator\Attribute\MediaComparator
    pim_catalog.comparator.attribute.prices.class:  Pim\Component\Catalog\Comparator\Attribute\PricesComparator
    pim_catalog.comparator.attribute.metric.class:  Pim\Component\Catalog\Comparator\Attribute\MetricComparator
    pim_catalog.comparator.attribute.option.class:  Pim\Component\Catalog\Comparator\Attribute\OptionComparator
    pim_catalog.comparator.attribute.options.class: Pim\Component\Catalog\Comparator\Attribute\OptionsComparator
    pim_catalog.comparator.attribute.scalar.class:  Pim\Component\Catalog\Comparator\Attribute\ScalarComparator
    pim_catalog.comparator.attribute.boolean.class: Pim\Component\Catalog\Comparator\Attribute\BooleanComparator
    pim_catalog.comparator.field.boolean.class:     Pim\Component\Catalog\Comparator\Field\BooleanComparator
    pim_catalog.comparator.field.scalar.class:      Pim\Component\Catalog\Comparator\Field\ScalarComparator
    pim_catalog.comparator.field.array.class:       Pim\Component\Catalog\Comparator\Field\ArrayComparator

services:
    pim_catalog.comparator.registry:
        public: false
        class: %pim_catalog.comparator.registry.class%

    ##
    # Comparators of product values
    ##
    pim_catalog.comparator.attribute.media:
        class: %pim_catalog.comparator.attribute.media.class%
        tags:
            - { name: pim_catalog.attribute.comparator }

    pim_catalog.comparator.attribute.prices:
        class: %pim_catalog.comparator.attribute.prices.class%
        tags:
            - { name: pim_catalog.attribute.comparator }

    pim_catalog.comparator.attribute.metric:
        class: %pim_catalog.comparator.attribute.metric.class%
        tags:
            - { name: pim_catalog.attribute.comparator }

    pim_catalog.comparator.attribute.option:
        class: %pim_catalog.comparator.attribute.option.class%
        tags:
            - { name: pim_catalog.attribute.comparator }

    pim_catalog.comparator.attribute.options:
        class: %pim_catalog.comparator.attribute.options.class%
        tags:
            - { name: pim_catalog.attribute.comparator }

    pim_catalog.comparator.attribute.boolean:
        class: %pim_catalog.comparator.attribute.boolean.class%
        tags:
            - { name: pim_catalog.attribute.comparator, priority: -100 }

    pim_catalog.comparator.attribute.scalar:
        class: %pim_catalog.comparator.attribute.scalar.class%
        tags:
            - { name: pim_catalog.attribute.comparator, priority: -128 }

    ##
    # Comparators of product fields
    ##
    pim_catalog.comparator.field.boolean:
        class: %pim_catalog.comparator.field.boolean.class%
        tags:
            - { name: pim_catalog.field.comparator }

    pim_catalog.comparator.field.array:
        class: %pim_catalog.comparator.field.array.class%
        tags:
            - { name: pim_catalog.field.comparator }

    pim_catalog.comparator.field.scalar:
        class: %pim_catalog.comparator.field.scalar.class%
        tags:
            - { name: pim_catalog.field.comparator, priority: -128 }
