parameters: ~

services:
    pim_catalog.controller.abstract:
        abstract: true
        arguments:
            - '@request'
            - '@templating'
            - '@router'
            - '@security.context'
            - '@form.factory'
            - '@validator'
            - '@translator'

    pim_catalog.controller.abstract_doctrine:
        abstract: true
        parent: pim_catalog.controller.abstract
        arguments:
            - '@doctrine'
