parameters: ~

services:
    pim_catalog.event_listener.association_grid_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_grid.class%
        arguments:
          - [localeCode]
          - @oro_datagrid.datagrid.request_params
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.association-type-grid, method: onBuildAfter }

    pim_catalog.event_listener.group_type_grid_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_grid.class%
        arguments:
          - [localeCode]
          - @oro_datagrid.datagrid.request_params
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.group-type-grid, method: onBuildAfter }

    pim_catalog.event_listener.attribute_grid_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_grid.class%
        arguments:
          - [localeCode]
          - @oro_datagrid.datagrid.request_params
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.attribute-grid, method: onBuildAfter }

    pim_catalog.event_listener.channel_grid_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_grid.class%
        arguments:
          - [localeCode]
          - @oro_datagrid.datagrid.request_params
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.channel-grid, method: onBuildAfter }

    pim_catalog.event_listener.family_grid_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_grid.class%
        arguments:
          - [localeCode]
          - @oro_datagrid.datagrid.request_params
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.family-grid, method: onBuildAfter }

    pim_catalog.event_listener.product_grid_before_listener:
        class: %pim_datagrid.event_listener.configure_flexible_grid_listener.class%
        arguments:
            - @pim_flexibleentity.registry
            - @pim_datagrid.datagrid.flexible.configuration_registry
            - @oro_datagrid.datagrid.request_params
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.product-grid, method: buildBefore}

    pim_catalog.event_listener.product_grid_after_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_product_grid.class%
        arguments:
          - [dataLocale]
          - @oro_datagrid.datagrid.request_params
          - @pim_catalog.manager.product
          - @pim_catalog.manager.locale
          - @pim_catalog.manager.channel
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.product-grid, method: onBuildAfter }

    pim_catalog.event_listener.product_group_grid_before_listener:
        class: %pim_datagrid.event_listener.configure_flexible_grid_listener.class%
        arguments:
            - @pim_flexibleentity.registry
            - @pim_datagrid.datagrid.flexible.configuration_registry
            - @oro_datagrid.datagrid.request_params
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.product-group-grid, method: buildBefore}

    pim_catalog.event_listener.product_group_grid_after_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_grid.class%
        arguments:
          - [dataLocale, currentGroup]
          - @oro_datagrid.datagrid.request_params
          - true
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.product-group-grid, method: onBuildAfter }

    pim_catalog.event_listener.group_grid_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_grid.class%
        arguments:
          - [localeCode, groupTypes]
          - @oro_datagrid.datagrid.request_params
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.group-grid, method: onBuildAfter }

    pim_catalog.event_listener.variant_group_grid_listener:
        class: %pim_datagrid.event_listener.add_parameters_to_grid.class%
        arguments:
          - [localeCode, groupTypes]
          - @oro_datagrid.datagrid.request_params
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.variant-group-grid, method: onBuildAfter }
