parameters:
    doctrine.orm.cache.apc.class:       Pim\Bundle\CatalogBundle\Doctrine\ArrayApcCache
    pim_catalog.event_subscriber.resolve_target_repository.class: Pim\Bundle\CatalogBundle\EventSubscriber\ResolveTargetRepositorySubscriber

services:
    pim_catalog.event_subscriber.resolve_target_repository:
        class: %pim_catalog.event_subscriber.resolve_target_repository.class%
        public: false
        tags:
            - { name: doctrine.event_subscriber }
