parameters:
    doctrine.orm.cache.apc.class:       Pim\Bundle\CatalogBundle\Doctrine\ArrayApcCache
    pim_catalog.event_subscriber.resolve_target_repository.class: Pim\Bundle\CatalogBundle\EventSubscriber\ResolveTargetRepositorySubscriber

services:
    pim_catalog.event_subscriber.resolve_target_repository:
        class: %pim_catalog.event_subscriber.resolve_target_repository.class%
        public: false
        tags:
            - { name: doctrine.event_subscriber }

    # deprecetad: will be removed in 1.4
    pim_catalog.doctrine.smart_manager_registry:
        alias: akeneo_doctrine_extensions.doctrine.smart_manager_registry

    # deprecetad: will be removed in 1.4
    pim_catalog.doctrine.table_name_builder:
        alias: akeneo_doctrine_extensions.doctrine.table_name_builder
