parameters:
    doctrine.orm.cache.apc.class: Pim\Bundle\CatalogBundle\Doctrine\ArrayApcCache
    pim_catalog.doctrine.object_detacher.class:     Pim\Bundle\CatalogBundle\Doctrine\Common\Persistence\Detacher

services:
    # deprecetad: will be removed in 1.4
    pim_catalog.event_subscriber.resolve_target_repository:
        alias: akeneo_storage_utils.event_subscriber.resolve_target_repository

    # deprecetad: will be removed in 1.4
    pim_catalog.doctrine.smart_manager_registry:
        alias: akeneo_storage_utils.doctrine.smart_manager_registry

    # deprecetad: will be removed in 1.4
    pim_catalog.doctrine.table_name_builder:
        alias: akeneo_storage_utils.doctrine.table_name_builder

    # TODO : new service and class should be move in AkeneoStorageUtils, add specs too
    pim_catalog.doctrine.object_detacher:
        class: %pim_catalog.doctrine.object_detacher.class%
        arguments:
            - '@pim_catalog.doctrine.smart_manager_registry'