parameters:
    pim_catalog.event_listener.create_attribute_requirement.class: Pim\Bundle\CatalogBundle\EventListener\CreateAttributeRequirementSubscriber
    pim_catalog.event_listener.metric_base_values.class:           Pim\Bundle\CatalogBundle\EventListener\MetricBaseValuesSubscriber
    pim_catalog.event_listener.localizable.class:                  Pim\Bundle\CatalogBundle\EventListener\LocalizableListener
    pim_catalog.event_listener.scopable.class:                     Pim\Bundle\CatalogBundle\EventListener\ScopableListener
    pim_catalog.event_listener.timestampable.class:                Pim\Bundle\CatalogBundle\EventListener\TimestampableListener

services:
    # Subscribers
    pim_catalog.event_listener.create_attribute_requirement:
        class: %pim_catalog.event_listener.create_attribute_requirement.class%
        arguments:
            - '@pim_catalog.factory.attribute_requirement'
        tags:
            - { name: doctrine.event_subscriber }

    pim_catalog.event_listener.metric_base_values:
        class: %pim_catalog.event_listener.metric_base_values.class%
        arguments:
            - '@akeneo_measure.measure_converter'
            - '@akeneo_measure.manager'
        tags:
            - { name: doctrine.event_subscriber }
            - { name: doctrine_mongodb.odm.event_subscriber }

    pim_catalog.event_listener.localizable:
        class: %pim_catalog.event_listener.localizable.class%
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: doctrine.event_subscriber }
            - { name: doctrine_mongodb.odm.event_subscriber }

    pim_catalog.event_listener.scopable:
        class: %pim_catalog.event_listener.scopable.class%
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: doctrine.event_subscriber }
            - { name: doctrine_mongodb.odm.event_subscriber }

    pim_catalog.event_listener.timestampable:
        class: %pim_catalog.event_listener.timestampable.class%
        tags:
            - { name: doctrine.event_subscriber }
