parameters:
    pim_catalog.family_variant.provider.can_have_family_variant_attributes.class: Pim\Component\Catalog\FamilyVariant\CanHaveFamilyVariantAttributesProvider

services:
    pim_catalog.family_variant.provider.can_have_family_variant_attributes:
        class: '%pim_catalog.family_variant.provider.can_have_family_variant_attributes.class%'
