services:
    pim_catalog.form.type.product.view:
        public: false
        class: %pim_catalog.form.type.product.view.class%

    pim_catalog.form.type.product:
        class: %pim_catalog.form.type.product.class%
        tags:
            - { name: form.type, alias: pim_product }

    pim_catalog.form.type.product_edit:
        class: %pim_catalog.form.type.product_edit.class%
        arguments:
            - '@pim_catalog.form.type.product.view'
        tags:
            - { name: form.type, alias: pim_product_edit }

    pim_catalog.form.type.product_create:
        class: %pim_catalog.form.type.product_create.class%
        tags:
            - { name: form.type, alias: pim_product_create }

    pim_catalog.form.type.product_value:
        class: %pim_catalog.form.type.product_value.class%
        arguments:
            - %pim_catalog.entity.product_value.class%
            - '@pim_flexibleentity.value_form.value_subscriber'
            - '@pim_catalog.form.type.product.view'
        tags:
            - { name: form.type, alias: pim_product_value }

    pim_catalog.form.type.attribute:
        class: %pim_catalog.form.type.attribute.class%
        tags:
            - { name: form.type, alias: pim_catalog_attribute }
        arguments:
            - %pim_catalog.entity.attribute.class%
            - '@pim_catalog.manager.attribute'
            - '@pim_catalog.form.subscriber.attribute'

    pim_catalog.form.type.attribute_option:
        class: %pim_catalog.form.type.attribute_option.class%
        tags:
            - { name: form.type, alias: pim_catalog_attribute_option }

    pim_catalog.form.type.attribute_option_value:
        class: %pim_catalog.form.type.attribute_option_value.class%
        tags:
            - { name: form.type, alias: pim_catalog_attribute_option_value }

    pim_catalog.form.type.attribute_option_create:
        class: %pim_catalog.form.type.attribute_option_create.class%
        tags:
            - { name: form.type, alias: pim_attribute_option_create }

    pim_catalog.form.type.attribute_group:
        class: %pim_catalog.form.type.attribute_group.class%
        tags:
            - { name: form.type, alias: pim_catalog_attribute_group }

    pim_catalog.form.type.family:
        class: %pim_catalog.form.type.family.class%
        tags:
            - { name: form.type, alias: pim_catalog_family }
        arguments:
            - '@pim_catalog.form.subscriber.attribute_requirements'
            - %pim_catalog.entity.attribute.class%
    pim_catalog.form.type.attribute_requirement:
        class: %pim_catalog.form.type.attribute_requirement.class%
        tags:
            - { name: form.type, alias: pim_catalog_attribute_requirement }

    pim_catalog.form.type.wysiwyg:
        class: %pim_catalog.form.type.product_value_wysiwyg.class%
        tags:
            - { name: form.type, alias: pim_wysiwyg }

    pim_catalog.form.type.price:
        class: %pim_catalog.form.type.product_value_price.class%
        tags:
            - { name: form.type, alias: pim_catalog_price }

    pim_catalog.form.type.price_collection:
        class: %pim_catalog.form.type.product_value_price_collection.class%
        tags:
            - { name: form.type, alias: pim_catalog_price_collection }

    pim_catalog.form.type.category:
        class: %pim_catalog.form.type.category.class%
        arguments:
            - %pim_catalog.entity.category.class%
            - %pim_catalog.entity.category_translation.class%
        tags:
            - { name: form.type, alias: pim_category }

    pim_catalog.form.type.channel:
        class: %pim_catalog.form.type.channel.class%
        arguments:
            - '@pim_catalog.manager.locale'
            - '@pim_catalog.helper.locale'
        tags:
            - { name: form.type, alias: pim_catalog_channel }

    pim_catalog.form.type.currency:
        class: %pim_catalog.form.type.currency.class%
        arguments:
            - '@pim_catalog.helper.locale'
        tags:
            - { name: form.type, alias: pim_catalog_currency }

    pim_catalog.form.type.edit_common_attributes:
        class: %pim_catalog.form.type.edit_common_attributes.class%
        arguments:
            - '@pim_catalog.form.type.product.view'
            - '@pim_catalog.helper.locale'
            - %pim_catalog.entity.attribute.class%
        tags:
            - { name: form.type, alias: pim_catalog_mass_edit_common_attributes }

    pim_catalog.form.type.add_to_groups:
        class: %pim_catalog.form.type.add_to_groups.class%
        tags:
            - { name: form.type, alias: pim_catalog_mass_add_to_groups }

    pim_catalog.form.type.localized_collection:
        class: %pim_catalog.form.type.localized_collection.class%
        tags:
            - { name: form.type, alias: pim_catalog_localized_collection }

    pim_catalog.form.type.group:
        class: %pim_catalog.form.type.group.class%
        arguments:
            - %pim_catalog.entity.attribute.class%
        tags:
            - { name: form.type, alias: pim_catalog_group }

    pim_catalog.form.type.group_type:
        class: %pim_catalog.form.type.group_type.class%
        tags:
            - { name: form.type, alias: pim_catalog_group_type }

    pim_catalog.form.type.association_type:
        class: %pim_catalog.form.type.association_type.class%
        tags:
            - { name: form.type, alias: pim_catalog_association_type }

    pim_catalog.form.type.available_attributes:
        class: %pim_catalog.form.type.available_attributes.class%
        arguments:
            - %pim_catalog.entity.attribute.class%
        tags:
            - { name: form.type, alias: pim_available_attributes }

    pim_catalog.form.type.association:
        class: %pim_catalog.form.type.association.class%
        tags:
            - { name: form.type, alias: pim_catalog_association }

    pim_catalog.form.type.conversion_units:
        class: %pim_catalog.form.type.conversion_units.class%
        arguments:
            - '@oro_measure.manager'
            - '@doctrine.orm.entity_manager'
            - %pim_catalog.entity.attribute.class%
        tags:
            - { name: form.type, alias: pim_catalog_conversion_units }

    pim_catalog.form.type.image:
        class: %pim_catalog.form.type.image.class%
        tags:
            - { name: form.type, alias: pim_catalog_image }

    pim_catalog.form.type.datagrid_configuration:
        class: %pim_catalog.form.type.datagrid_configuration.class%
        tags:
            - { name: form.type, alias: pim_catalog_datagrid_configuration }

    # Form extensions

    pim_catalog.extension.type.media:
        class: %pim_catalog.extension.type.media.class%
        tags:
            - { name: form.type_extension, alias: oro_media }

    pim_catalog.extension.type.metric:
        class: %pim_catalog.extension.type.metric.class%
        tags:
            - { name: form.type_extension, alias: pim_flexibleentity_metric }
