parameters:
    pim_catalog.resolver.fqcn.class: Pim\Bundle\CatalogBundle\Resolver\FQCNResolver

services:
    pim_catalog.resolver.fqcn:
        class: %pim_catalog.resolver.fqcn.class%
        calls:
            - [setFQCN, ['product', '%pim_catalog.entity.product.class%']]
            - [setFQCN, ['product_value', '%pim_catalog.entity.product_value.class%']]
            - [setFQCN, ['association', '%pim_catalog.entity.association.class%']]
            - [setFQCN, ['completeness', '%pim_catalog.entity.completeness.class%']]
            - [setFQCN, ['association_type', '%pim_catalog.entity.association_type.class%']]
            - [setFQCN, ['category', '%pim_catalog.entity.category.class%']]
            - [setFQCN, ['category_translation', '%pim_catalog.entity.category_translation.class%']]
            - [setFQCN, ['group', '%pim_catalog.entity.group.class%']]
            - [setFQCN, ['group_type', '%pim_catalog.entity.group_type.class%']]
            - [setFQCN, ['attribute', '%pim_catalog.entity.attribute.class%']]
            - [setFQCN, ['attribute_translation', '%pim_catalog.entity.attribute_translation.class%']]
            - [setFQCN, ['attribute_group', '%pim_catalog.entity.attribute_group.class%']]
            - [setFQCN, ['attribute_group_translation', '%pim_catalog.entity.attribute_group_translation.class%']]
            - [setFQCN, ['attribute_option', '%pim_catalog.entity.attribute_option.class%']]
            - [setFQCN, ['attribute_option_value', '%pim_catalog.entity.attribute_option_value.class%']]
            - [setFQCN, ['attribute_requirement', '%pim_catalog.entity.attribute_requirement.class%']]
            - [setFQCN, ['family', '%pim_catalog.entity.family.class%']]
            - [setFQCN, ['family_translation', '%pim_catalog.entity.family_translation.class%']]
            - [setFQCN, ['channel', '%pim_catalog.entity.channel.class%']]
            - [setFQCN, ['currency', '%pim_catalog.entity.currency.class%']]
            - [setFQCN, ['locale', '%pim_catalog.entity.locale.class%']]
            - [setFQCN, ['metric', '%pim_catalog.entity.metric.class%']]
            - [setFQCN, ['product_media', '%pim_catalog.entity.product_media.class%']]
            - [setFQCN, ['product_price', '%pim_catalog.entity.product_price.class%']]
            - [setFQCN, ['product_template', '%pim_catalog.entity.product_template.class%']]
            - [setFQCN, ['available_attributes', '%pim_catalog.entity.available_attributes.class%']]
