attributegroup:
    resource: '@PimCatalogBundle/Resources/config/routing/attributegroup.yml'
    prefix: /configuration/attribute-group

channel:
    resource: '@PimCatalogBundle/Resources/config/routing/channel.yml'
    prefix: /configuration/channel

currency:
    resource: '@PimCatalogBundle/Resources/config/routing/currency.yml'
    prefix: /configuration/currency

family:
    resource: '@PimCatalogBundle/Resources/config/routing/family.yml'
    prefix: /configuration/family

locale:
    resource: '@PimCatalogBundle/Resources/config/routing/locale.yml'
    prefix: /configuration/locale

attribute:
    resource: '@PimCatalogBundle/Resources/config/routing/attribute.yml'
    prefix: /configuration/attribute

categorytree:
    resource: '@PimCatalogBundle/Resources/config/routing/categorytree.yml'
    prefix: /enrich/category-tree

product:
    resource: '@PimCatalogBundle/Resources/config/routing/product.yml'
    prefix: /enrich/product

mass_edit_action:
    resource: '@PimCatalogBundle/Resources/config/routing/mass_edit_action.yml'
    prefix: /enrich/mass-edit-action

variant_group:
    resource: '@PimCatalogBundle/Resources/config/routing/variant_group.yml'
    prefix: /enrich/variant-group

group:
    resource: '@PimCatalogBundle/Resources/config/routing/group.yml'
    prefix: /enrich/group

association:
    resource: '@PimCatalogBundle/Resources/config/routing/associationtype.yml'
    prefix: /configuration/association-type

media:
    resource: '@PimCatalogBundle/Resources/config/routing/media.yml'
    prefix: /media

grouptype:
    resource: '@PimCatalogBundle/Resources/config/routing/grouptype.yml'
    prefix: /configuration/group-type

datagrid:
    resource: '@PimCatalogBundle/Resources/config/routing/datagrid.yml'
    prefix: /datagrid
