parameters:
    pim_catalog.saver.base.class:                     Pim\Bundle\CatalogBundle\Saver\BaseSaver
    pim_catalog.saver.product.class:                  Pim\Bundle\CatalogBundle\Saver\ProductSaver
    pim_catalog.saver.product_options_resolver.class: Pim\Bundle\CatalogBundle\Saver\ProductSavingOptionsResolver
    pim_catalog.saver.base_options_resolver.class:    Pim\Bundle\CatalogBundle\Saver\BaseSavingOptionsResolver

services:
    pim_catalog.saver.group_type:
        class: %pim_catalog.saver.base.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.saver.base_options_resolver'
            - %pim_catalog.entity.group_type.class%

    pim_catalog.saver.currency:
        class: %pim_catalog.saver.base.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.saver.base_options_resolver'
            - %pim_catalog.entity.currency.class%

    pim_catalog.saver.product:
        class: %pim_catalog.saver.product.class%
        arguments:
            - '@pim_catalog.object_manager.product'
            - '@pim_catalog.manager.completeness'
            - '@pim_catalog.saver.product_options_resolver'

    pim_catalog.saver.base_options_resolver:
        class: %pim_catalog.saver.base_options_resolver.class%

    pim_catalog.saver.product_options_resolver:
        class: %pim_catalog.saver.product_options_resolver.class%
