parameters:
    pim_catalog.saver.base.class:                     Akeneo\Bundle\StorageUtilsBundle\Doctrine\Common\Saver\BaseSaver
    pim_catalog.saver.base_options_resolver.class:    Akeneo\Bundle\StorageUtilsBundle\Doctrine\Common\Saver\BaseSavingOptionsResolver
    pim_catalog.saver.product.class:                  Pim\Bundle\CatalogBundle\Doctrine\Common\Saver\ProductSaver
    pim_catalog.saver.product_options_resolver.class: Pim\Bundle\CatalogBundle\Doctrine\Common\Saver\ProductSavingOptionsResolver

services:
    pim_catalog.saver.group_type:
        class: %pim_catalog.saver.base.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.saver.base_options_resolver'
            - %pim_catalog.model.group_type.interface%

    pim_catalog.saver.currency:
        class: %pim_catalog.saver.base.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.saver.base_options_resolver'
            - %pim_catalog.model.currency.interface%

    pim_catalog.saver.product:
        class: %pim_catalog.saver.product.class%
        arguments:
            - '@pim_catalog.object_manager.product'
            - '@pim_catalog.manager.completeness'
            - '@pim_catalog.saver.product_options_resolver'

    pim_catalog.saver.base_options_resolver:
        class: %pim_catalog.saver.base_options_resolver.class%

    pim_catalog.saver.product_options_resolver:
        class: %pim_catalog.saver.product_options_resolver.class%
