parameters:
    pim_catalog.normalizer.indexing.product.class: Pim\Component\Catalog\Normalizer\Indexing\ProductNormalizer
    pim_catalog.normalizer.indexing.product.properties.class: Pim\Component\Catalog\Normalizer\Indexing\Product\PropertiesNormalizer
    pim_catalog.normalizer.indexing.datetime.class: Pim\Component\Catalog\Normalizer\Indexing\DateTimeNormalizer
    pim_catalog.normalizer.indexing.product.product_value_collection.class: Pim\Component\Catalog\Normalizer\Indexing\Product\ProductValueCollectionNormalizer
    pim_catalog.normalizer.indexing.product.completeness_collection.class: Pim\Component\Catalog\Normalizer\Indexing\Product\CompletenessCollectionNormalizer

services:
    pim_catalog.normalizer.indexing.product:
        class: '%pim_catalog.normalizer.indexing.product.class%'
        arguments:
            - '@pim_catalog.normalizer.indexing.product.properties'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.properties:
        class: '%pim_catalog.normalizer.indexing.product.properties.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 40 }

    pim_catalog.normalizer.indexing.datetime:
        class: '%pim_catalog.normalizer.indexing.datetime.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.datetime'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.product_value_collection:
        class: '%pim_catalog.normalizer.indexing.product.product_value_collection.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.indexing.product.completeness_collection:
        class: '%pim_catalog.normalizer.indexing.product.completeness_collection.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
