parameters:
    pim_catalog.imagine.local_dir_resolver.class:                  Pim\Bundle\CatalogBundle\Imagine\Cache\Resolver\LocalDirResolver
    pim_catalog.event_listener.progress.class:                     Pim\Bundle\CatalogBundle\EventListener\ProgressListener
    pim_catalog.event_listener.create_attribute_requirement.class: Pim\Bundle\CatalogBundle\EventListener\CreateAttributeRequirementSubscriber
    pim_catalog.event_listener.metric_base_values.class:           Pim\Bundle\CatalogBundle\EventListener\MetricBaseValuesSubscriber

services:
    # Subscribers
    pim_catalog.event_listener.user_preferences:
        class: %pim_catalog.event_listener.user_preferences.class%
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: doctrine.event_subscriber }

    pim_catalog.event_listener.create_attribute_requirement:
        class: %pim_catalog.event_listener.create_attribute_requirement.class%
        arguments:
            - '@pim_catalog.factory.attribute_requirement'
        tags:
            - { name: doctrine.event_subscriber }

    pim_catalog.event_listener.progress:
        class: %pim_catalog.event_listener.progress.class%
        arguments:
            - '@event_dispatcher'

    pim_catalog.event_listener.request:
        class: Pim\Bundle\CatalogBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_subscriber }

    pim_catalog.event_listener.metric_base_values:
        class: %pim_catalog.event_listener.metric_base_values.class%
        arguments:
            - '@oro_measure.measure_converter'
            - '@oro_measure.manager'
        tags:
            - { name: doctrine.event_subscriber }

    # Validators
    pim_catalog.form.validator.metric:
        class: Pim\Bundle\CatalogBundle\Validator\Constraints\ValidMetricValidator
        arguments:
            - '@property_accessor'
            - %oro_measure.measures_config%
        tags:
            - { name: validator.constraint_validator, alias: pim_metric_validator }

    pim_catalog.form.validator.single_identifier_attribute:
        class: Pim\Bundle\CatalogBundle\Validator\Constraints\SingleIdentifierAttributeValidator
        arguments:
            - '@pim_catalog.manager.product'
        tags:
            - { name: validator.constraint_validator, alias: pim_single_identifier_attribute_validator }

    pim_catalog.form.validator.unique_variant_axis:
        class: Pim\Bundle\CatalogBundle\Validator\Constraints\UniqueVariantAxisValidator
        arguments:
            - '@pim_catalog.manager.product'
        tags:
            - { name: validator.constraint_validator, alias: pim_unique_variant_axis_validator }

    pim_catalog.validator.constraints.unique_value:
        class: Pim\Bundle\CatalogBundle\Validator\Constraints\UniqueValueValidator
        arguments:
            - '@doctrine'
        tags:
            - { name: validator.constraint_validator, alias: pim_unique_value_validator }

    pim_catalog.validator.valid_locale_fallback:
        class: Pim\Bundle\CatalogBundle\Validator\Constraints\ValidLocaleFallbackValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator, alias: pim_catalog.validator.valid_locale_fallback_validator }

    pim_catalog.validator.immutable:
        class: Pim\Bundle\CatalogBundle\Validator\Constraints\ImmutableValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator, alias: pim_immutable_validator }

    # Locale helper
    pim_catalog.helper.locale:
        class: Pim\Bundle\CatalogBundle\Helper\LocaleHelper
        arguments:
            - '@pim_catalog.manager.locale'

    pim_catalog.twig.locale_extension:
        class: Pim\Bundle\CatalogBundle\Twig\LocaleExtension
        arguments:
            - '@pim_catalog.helper.locale'
        tags:
            - { name: twig.extension }

    pim_catalog.twig.category_extension:
        class: Pim\Bundle\CatalogBundle\Twig\CategoryExtension
        arguments:
            - '@pim_catalog.manager.category'
            - '@pim_catalog.manager.product'
        tags:
            - { name: twig.extension }

    pim_catalog.twig.object_class_extension:
        class: Pim\Bundle\CatalogBundle\Twig\ObjectClassExtension
        tags:
            - { name: twig.extension }

    # extension listener
    stof_doctrine_extensions.event_listener.locale:
        class: %pim_catalog.event_listener.user_context.class%
        arguments:
            - '@security.context'
            - '@pim_translation.listener.add_locale'
            - '@pim_catalog.manager.product'
        tags:
            - { name: kernel.event_subscriber }

    # Media management
    pim_catalog.imagine.local_dir_resolver:
        class: %pim_catalog.imagine.local_dir_resolver.class%
        parent: liip_imagine.cache.resolver.web_path
        arguments:
            - %kernel.cache_dir%/media
        tags:
            - { name: liip_imagine.cache.resolver, resolver: 'local_dir' }
