Pim\Bundle\DataGridBundle\Entity\DatagridView:
    type:  entity
    table: pim_datagrid_view
    repositoryClass: Pim\Bundle\DataGridBundle\Entity\Repository\DatagridViewRepository
    fields:
        id:
            type: integer
            id:   true
            generator:
                strategy: AUTO
        label:
            type:     string
            length:   100
            unique:   true
            nullable: true
        type:
            type:     string
            length:   10
            nullable: true
        datagridAlias:
            type:   string
            column: datagrid_alias
        columns:
            type: array
        configuredColumns:
            type: array
        filters:
            type:     text
            nullable: true

    manyToOne:
        owner:
            targetEntity: Oro\Bundle\UserBundle\Entity\User
            joinColumns:
                owner_id:
                    referencedColumnName: id
                    onDelete:             CASCADE
