parameters:
    akeneo_elasticsearch.cursor.cursor.class: Akeneo\Bundle\ElasticsearchBundle\Cursor\Cursor
    akeneo_elasticsearch.cursor.search_after_bounded_cursor.class: Akeneo\Bundle\ElasticsearchBundle\Cursor\SearchAfterBoundedCursor
    akeneo_elasticsearch.cursor.from_size_cursor.class: Akeneo\Bundle\ElasticsearchBundle\Cursor\FromSizeCursor
    akeneo_elasticsearch.cursor.cursor_factory.class: Akeneo\Bundle\ElasticsearchBundle\Cursor\CursorFactory
    akeneo_elasticsearch.cursor.search_after_bounded_cursor_factory.class: Akeneo\Bundle\ElasticsearchBundle\Cursor\SearchAfterBoundedCursorFactory
    akeneo_elasticsearch.cursor.from_size_cursor_factory.class: Akeneo\Bundle\ElasticsearchBundle\Cursor\FromSizeCursorFactory
