parameters:
    pim_flexibleentity.grid.extension.formatter.property.class:       Pim\Bundle\FlexibleEntityBundle\Grid\Extension\Formatter\Property\FlexibleFieldProperty


services:

    pim_flexibleentity.grid.extension.formatter.property:
        class: %pim_flexibleentity.grid.extension.formatter.property.class%
        arguments:
            - @translator
        tags:
            - { name:  oro_datagrid.extension.formatter.property, type: flexible_field }

