parameters:
    pim_flexibleentity.grid.listener.class:                           Pim\Bundle\FlexibleEntityBundle\Grid\EventListener
    pim_flexibleentity.grid.extension.formatter.property.class:       Pim\Bundle\FlexibleEntityBundle\Grid\Extension\Formatter\Property\FlexibleFieldProperty

    pim_flexibleentity.grid.extension.flexible_filter_utility.class:  Pim\Bundle\FlexibleEntityBundle\Grid\Extension\Filter\FilterUtility

    pim_flexibleentity.grid.extension.filter.string.class:            Pim\Bundle\FlexibleEntityBundle\Grid\Extension\Filter\FlexibleStringFilter
    pim_flexibleentity.grid.extension.filter.choice.class:            Pim\Bundle\FlexibleEntityBundle\Grid\Extension\Filter\FlexibleChoiceFilter
    pim_flexibleentity.grid.extension.filter.number.class:            Pim\Bundle\FlexibleEntityBundle\Grid\Extension\Filter\FlexibleNumberFilter
    pim_flexibleentity.grid.extension.filter.entity.class:            Pim\Bundle\FlexibleEntityBundle\Grid\Extension\Filter\FlexibleEntityFilter
    pim_flexibleentity.grid.extension.filter.date.class:              Pim\Bundle\FlexibleEntityBundle\Grid\Extension\Filter\FlexibleDateRangeFilter
    pim_flexibleentity.grid.extension.filter.datetime.class:          Pim\Bundle\FlexibleEntityBundle\Grid\Extension\Filter\FlexibleDateTimeRangeFilter
    pim_flexibleentity.grid.extension.filter.boolean.class:           Pim\Bundle\FlexibleEntityBundle\Grid\Extension\Filter\FlexibleBooleanFilter
    pim_flexibleentity.grid.extension.filter.metric.class:            Pim\Bundle\FlexibleEntityBundle\Grid\Extension\Filter\FlexibleMetricFilter
    pim_flexibleentity.grid.extension.filter.price.class:             Pim\Bundle\FlexibleEntityBundle\Grid\Extension\Filter\FlexiblePriceFilter

services:
    pim_flexibleentity.grid.listener:
        class: %pim_flexibleentity.grid.listener.class%
        arguments:
            - @pim_flexibleentity.registry
            - @oro_datagrid.datagrid.request_params
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before, method: buildBefore}
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after,  method: buildAfter}

    pim_flexibleentity.grid.extension.formatter.property:
        class: %pim_flexibleentity.grid.extension.formatter.property.class%
        arguments:
            - @translator
        tags:
            - { name:  oro_datagrid.extension.formatter.property, type: flexible_field }

    pim_flexibleentity.grid.extension.flexible_filter_utility:
        class: %pim_flexibleentity.grid.extension.flexible_filter_utility.class%
        arguments:
            - @pim_flexibleentity.registry

    pim_flexibleentity.grid.extension.filter.string:
        class: %pim_flexibleentity.grid.extension.filter.string.class%
        arguments:
            - @form.factory
            - @pim_flexibleentity.grid.extension.flexible_filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: flexible_string }

    pim_flexibleentity.grid.extension.filter.choice:
        class: %pim_flexibleentity.grid.extension.filter.choice.class%
        arguments:
            - @form.factory
            - @pim_flexibleentity.grid.extension.flexible_filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: flexible_choice }

    pim_flexibleentity.grid.extension.filter.number:
        class: %pim_flexibleentity.grid.extension.filter.number.class%
        arguments:
            - @form.factory
            - @pim_flexibleentity.grid.extension.flexible_filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: flexible_number }

    pim_flexibleentity.grid.extension.filter.entity:
        class: %pim_flexibleentity.grid.extension.filter.entity.class%
        arguments:
            - @form.factory
            - @pim_flexibleentity.grid.extension.flexible_filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: flexible_entity }

    pim_flexibleentity.grid.extension.filter.date:
        class: %pim_flexibleentity.grid.extension.filter.date.class%
        arguments:
            - @form.factory
            - @pim_flexibleentity.grid.extension.flexible_filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: flexible_date }

    pim_flexibleentity.grid.extension.filter.datetime:
        class: %pim_flexibleentity.grid.extension.filter.datetime.class%
        arguments:
            - @form.factory
            - @pim_flexibleentity.grid.extension.flexible_filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: flexible_datetime }

    pim_flexibleentity.grid.extension.filter.boolean:
        class: %pim_flexibleentity.grid.extension.filter.boolean.class%
        arguments:
            - @form.factory
            - @pim_flexibleentity.grid.extension.flexible_filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: flexible_boolean }

    pim_flexibleentity.grid.extension.filter.metric:
        class: %pim_flexibleentity.grid.extension.filter.metric.class%
        arguments:
            - @form.factory
            - @pim_flexibleentity.grid.extension.flexible_filter_utility
            - @translator
            - @oro_measure.manager
            - @oro_measure.measure_converter
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: flexible_metric }

    pim_flexibleentity.grid.extension.filter.price:
        class: %pim_flexibleentity.grid.extension.filter.price.class%
        arguments:
            - @form.factory
            - @pim_flexibleentity.grid.extension.flexible_filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: flexible_price }
