connector:
    name: Data fixtures
    jobs:
        fixtures_category_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_category
                        processor: pim_connector.processor.denormalization.category
                        writer:    pim_connector.writer.database.category
                    parameters:
                        batchSize: 1

        fixtures_attribute_group_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_attribute_group
                        processor: pim_connector.processor.denormalization.attribute_group
                        writer:    pim_connector.writer.database.attribute_group

        fixtures_channel_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_channel
                        processor: pim_connector.processor.denormalization.channel
                        writer:    pim_connector.writer.database.channel

        fixtures_locale_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_locale
                        processor: pim_connector.processor.denormalization.locale
                        writer:    pim_connector.writer.database.locale

        fixtures_currency_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_currency
                        processor: pim_connector.processor.denormalization.currency
                        writer:    pim_connector.writer.database.currency

        fixtures_group_type_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_group_type
                        processor: pim_connector.processor.denormalization.group_type
                        writer:    pim_connector.writer.database.group_type

        fixtures_association_type_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_association_type
                        processor: pim_connector.processor.denormalization.association_type
                        writer:    pim_connector.writer.database.association_type

        fixtures_attribute_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_attribute
                        processor: pim_connector.processor.denormalization.attribute
                        writer:    pim_connector.writer.database.attribute

        fixtures_attribute_options_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_attribute_option
                        processor: pim_connector.processor.denormalization.attribute_option
                        writer:    pim_connector.writer.database.attribute_option

        fixtures_family_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_family
                        processor: pim_connector.processor.denormalization.family
                        writer:    pim_connector.writer.database.family

        fixtures_variant_group_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_variant_group
                        processor: pim_connector.processor.denormalization.variant_group
                        writer:    pim_connector.writer.database.variant_group

        fixtures_product_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_product
                        processor: pim_connector.processor.denormalization.product
                        writer:    pim_connector.writer.database.product
                import_associations:
                    services:
                        reader:    pim_connector.reader.file.csv_association
                        processor: pim_connector.processor.denormalization.product_association
                        writer:    pim_connector.writer.database.product_association
                    parameters:
                        batch_size: 1

        fixtures_job_yml:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.yaml
                        processor: pim_connector.processor.denormalization.job_instance.flat
                        writer:    pim_connector.writer.database.job_instance

        fixtures_user_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_user
                        processor: pim_connector.processor.denormalization.user
                        writer:    pim_connector.writer.database.user

        fixtures_user_role_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_user_role
                        processor: pim_connector.processor.denormalization.user_role
                        writer:    pim_connector.writer.database.user_role

        fixtures_user_group_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_user_group
                        processor: pim_connector.processor.denormalization.user_group
                        writer:    pim_connector.writer.database.user_group

        fixtures_group_csv:
            type:  fixtures
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_group
                        processor: pim_connector.processor.denormalization.group
                        writer:    pim_connector.writer.database.group
