default:
    class: Pim\Bundle\InstallerBundle\FixtureLoader\Loader
    order: 100
    multiple: false
    csv:
        reader:            pim_import_export.reader.file.csv
        reader_options:    {}
        processor_options: {}
    yml:
        reader:            pim_import_export.reader.file.yaml
        reader_options:    {}
        processor_options: {}

categories:
    order: 30
    multiple: true
    csv:
        reader:            pim_import_export.reader.file.csv_category
        processor:         pim_import_export.processor.category
    yml:
        reader:            pim_import_export.reader.file.yaml_multiple
        processor:         pim_import_export.processor.category

attribute_groups:
    order: 30
    csv:
        processor:         pim_import_export.processor.attribute_group
    yml:
        processor:         pim_import_export.processor.attribute_group

channels:
    order: 30
    csv:
        processor:         pim_import_export.processor.channel
    yml:
        processor:         pim_import_export.processor.channel

group_types:
    order: 30
    csv:
        processor:         pim_import_export.processor.group_type
    yml:
        processor:         pim_import_export.processor.group_type

association_types:
    order: 40
    csv:
        processor:         pim_import_export.processor.association_type
    yml:
        processor:         pim_import_export.processor.association_type

attributes:
    order: 40
    csv:
        processor:         pim_import_export.processor.attribute
    yml:
        processor:         pim_import_export.processor.attribute

attribute_options:
    order: 50
    csv:
        processor:         pim_import_export.processor.attribute_option
    yml:
        processor:         pim_import_export.processor.attribute_option

families:
    order: 60
    csv:
        processor:         pim_import_export.processor.family
    yml:
        processor:         pim_import_export.processor.family

groups:
    order: 70
    csv:
        processor:         pim_import_export.processor.group
    yml:
        processor:         pim_import_export.processor.group

products:
    order: 80
    csv:
        processor:         pim_import_export.processor.product
    yml:
        reader:            pim_import_export.reader.file.yaml_product
        processor:         pim_import_export.processor.product

associations:
    order: 90
    csv:
        processor:         pim_import_export.processor.association
    yml:
        reader:            pim_import_export.reader.file.yaml_associations
        processor:         pim_import_export.processor.association

jobs:
    order: 90
    csv:
        processor:         pim_import_export.processor.job_instance
    yml:
        processor:         pim_import_export.processor.job_instance
