extensions:
    pim-job-execution-form:
        module: pim/form/common/edit-form

    pim-job-execution-form-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: pim-job-execution-form
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    pim-job-execution-form-download-file:
        module: pim/form/common/download-file
        parent: pim-job-execution-form
        targetZone: buttons
        aclResourceId: pim_pdf_generator_product_download
        position: 70
        config:
            label: pim_enrich.form.job_execution.button.download_file.title
            iconName: download-alt

    pim-job-execution-form-download-archive:
        module: pim/form/common/download-file
        parent: pim-job-execution-form
        targetZone: buttons
        aclResourceId: pim_pdf_generator_product_download
        position: 80
        config:
            label: pim_enrich.form.job_execution.button.download_archive.title
            iconName: download-alt

    pim-job-execution-form-download-log:
        module: pim/form/common/download-file
        parent: pim-job-execution-form
        targetZone: buttons
        aclResourceId: pim_pdf_generator_product_download
        position: 90
        config:
            label: pim_enrich.form.job_execution.button.download_log.title
            iconName: download-alt
            url: pim_importexport_export_execution_download_log
            urlParams:
              - property: id
                path: meta.jobId

    pim-job-execution-form-show-profile:
        module: pim/common/redirect
        parent: pim-job-execution-form
        targetZone: buttons
        position: 100
        config:
            iconName: eye-open
            label: pim_enrich.form.job_execution.button.show_profile.title
            route: pim_importexport_import_profile_edit
            identifier:
                path: code
                name: code

    pim-job-execution-form-status:
        module: pim/form/common/meta/status
        parent: pim-job-execution-form
        targetZone: meta
        position: 90
        config:
            label: pim_enrich.form.job_execution.meta.status.title
            valuePath: status
            updateOnEvent : pim-job-execution-form:newData

    pim-job-execution-form-label:
        module: pim/job/common/label
        parent: pim-job-execution-form
        targetZone: title
        position: 100

    pim-job-execution-form-auto-refresh:
        module: pim/job/execution/auto-refresh
        parent: pim-job-execution-form
        targetZone: content
        position: 90

    pim-job-execution-form-summary-table:
        module: pim/job/execution/summary-table
        parent: pim-job-execution-form
        targetZone: content
        position: 100