pim_datagrid_view_index:
    path: /{alias}
    defaults: { _controller: pim_datagrid.controller.datagrid_view:indexAction }
    requirements:
        _method: GET|POST

pim_datagrid_view_list_columns:
    path: /{alias}/columns
    defaults: { _controller: pim_datagrid.controller.datagrid_view:listColumnsAction }
    requirements:
        _method: GET

pim_datagrid_view_remove:
    path: /{id}/remove
    defaults: { _controller: pim_datagrid.controller.datagrid_view:removeAction }
    requirements:
        id: \d+
    methods: [DELETE]
