pim_datagrid_export_index:
    path: '/index'
    defaults: { _controller: pim_datagrid.controller.export:indexAction }

pim_datagrid_export_flexible_index:
    path: '/flexible/index'
    defaults: { _controller: pim_datagrid.controller.flexible_export:indexAction }
