pim_enrich_attributeoption_index:
    path: /{attributeId}
    defaults: { _controller: pim_enrich.controller.attribute_option:indexAction }
    methods: [GET]
    requirements:
        attributeId: \d+

pim_enrich_attributeoption_create:
    path: /{attributeId}
    defaults: { _controller: pim_enrich.controller.attribute_option:createAction }
    methods: [POST]
    requirements:
        attributeId: \d+

pim_enrich_attributeoption_update:
    path: /{attributeId}/{attributeOptionId}
    defaults: { _controller: pim_enrich.controller.attribute_option:updateAction }
    methods: [PUT]
    requirements:
        attributeId: \d+
        attributeOptionId: \d+

pim_enrich_attributeoption_delete:
    path: /{attributeId}/{attributeOptionId}
    defaults: { _controller: pim_enrich.controller.attribute_option:deleteAction }
    methods: [DELETE]
    requirements:
        attributeId: \d+
        attributeOptionId: \d+

pim_enrich_attributeoption_update_sorting:
    path: /{attributeId}/update-sorting
    defaults: { _controller: pim_enrich.controller.attribute_option:updateSortingAction }
    methods: [PUT]
    requirements:
        attributeId: \d+

pim_enrich_attributeoption_get:
    path: /attribute/{identifier}/option
    defaults: { _controller: pim_enrich.controller.rest.attribute_option:getAction }
    methods: [GET]
    requirements:
        identifier: '[a-zA-Z0-9_]+'
