pim_enrich_form_extension_rest_index:
    path: /extensions.{_format}
    defaults: { _controller: pim_enrich.controller.form_extension_rest:getAction, _format: json }
    requirements:
        method: GET
        _format: json
