pim_enrich_grouptype_index:
    path: ''
    defaults: { _controller: pim_enrich.controller.group_type:indexAction }

pim_enrich_grouptype_create:
    path: /create
    defaults: { _controller: pim_enrich.controller.group_type:createAction }

pim_enrich_grouptype_edit:
    path: /{code}/edit
    defaults: { _controller: pim_enrich.controller.group_type:editAction }
    requirements:
        code: '[a-zA-Z0-9_]+'

pim_enrich_grouptype_rest_index:
    path: /rest
    defaults: { _controller: pim_enrich.controller.rest.group_type:indexAction }
    methods: [GET]

pim_enrich_grouptype_rest_get:
    path: /rest/{identifier}
    defaults: { _controller: pim_enrich.controller.rest.group_type:getAction }
    methods: [GET]
    requirements:
        identifier: '[a-zA-Z0-9_]+'

pim_enrich_grouptype_rest_post:
    path: /rest/{code}
    defaults: { _controller: pim_enrich.controller.rest.group_type:postAction }
    methods: [POST]
    requirements:
        code: '[a-zA-Z0-9_]+'

pim_enrich_grouptype_rest_remove:
    path: /rest/{code}
    defaults: { _controller: pim_enrich.controller.rest.group_type:removeAction }
    methods: [DELETE]
    requirements:
        code: '[a-zA-Z0-9_]+'
