pim_enrich_locale_index:
    path: /
    defaults: { _controller: pim_enrich.controller.locale:indexAction }

pim_enrich_locale_rest_index:
    path: /rest
    defaults: { _controller: pim_enrich.controller.locale_rest:indexAction, _format: json }
    methods: [GET]
