pim_enrich_mass_edit_action_choose:
    path: /choose/mass-edit
    defaults: { _controller: pim_enrich.controller.mass_edit_action:chooseAction, operationGroup: mass_edit }
    requirements:
        _method: GET|POST

pim_enrich_category_edit_action_choose:
    path: /choose/category-edit
    defaults: { _controller: pim_enrich.controller.mass_edit_action:chooseAction, operationGroup: category_edit }
    requirements:
        _method: GET|POST

pim_enrich_mass_edit_action_configure:
    path: /{operationAlias}/configure
    defaults: { _controller: pim_enrich.controller.mass_edit_action:configureAction }
    requirements:
        _method: GET|POST

pim_enrich_mass_edit_action_perform:
    path: /{operationAlias}/perform
    defaults: { _controller: pim_enrich.controller.mass_edit_action:performAction }
    requirements:
        _method: POST
