pim_enrich_media_show:
    path: /show/{filename}/{filter}
    defaults: { _controller: pim_enrich.controller.file_display:showAction, filter: null }
    methods: [GET]

pim_enrich_media_download:
    path: /download/{filename}
    defaults: { _controller: pim_enrich.controller.file_display:downloadAction, filter: null }
    methods: [GET]
