parameters:
    pim_reference_data.provider.field.reference_data.class: Pim\Bundle\ReferenceDataBundle\Provider\Field\ReferenceDataFieldProvider

services:
    pim_reference_data.provider.field.reference_data:
        class: %pim_reference_data.provider.field.reference_data.class%
        tags:
            - { name: pim_enrich.provider.field, priority: 100 }
