services:
    pim_reference_data.doctrine.query.filter.reference_data:
        class: %pim_reference_data.doctrine.query.filter.reference_data.class%
        arguments:
            - @pim_catalog.validator.helper.attribute
            - '@pim_reference_data.registry'
            - ['IN', 'EMPTY']
        tags:
            - { name: 'pim_catalog.doctrine.query.filter', priority: 30 }
