parameters:
    pim_reference_data.registry.class: Pim\Component\ReferenceData\ConfigurationRegistry
    pim_reference_data.method_guesser.class: Pim\Component\ReferenceData\MethodNameGuesser

services:
    pim_reference_data.registry:
        class: %pim_reference_data.registry.class%
    pim_reference_data.method_guesser:
        class: %pim_reference_data.method_guesser.class%
