parameters:
    pim_reference_data.extension.sorter.reference_data_sorter.class: Pim\Bundle\ReferenceDataBundle\Extension\Sorter\ReferenceDataSorter
    pim_reference_data.doctrine.query.sorter.reference_data.class: Pim\Bundle\ReferenceDataBundle\Doctrine\ORM\Sorter\ReferenceDataSorter

services:
    pim_reference_data.extension.sorter.reference_data_sorter:
        class: %pim_reference_data.extension.sorter.reference_data_sorter.class%
        arguments:
            - '@oro_datagrid.datagrid.request_params'
        tags:
            - { name: pim_datagrid.extension.sorter, type: product_value_reference_data }

    pim_reference_data.doctrine.query.sorter.reference_data:
        class: %pim_reference_data.doctrine.query.sorter.reference_data.class%
        arguments:
            - '@pim_reference_data.registry'
        tags:
            - { name: 'pim_catalog.doctrine.query.sorter', priority: 30 }
