connector:
    name: Akeneo CSV Connector
    jobs:
        csv_variant_group_import:
            type:  import
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_variant_group
                        processor: pim_connector.processor.denormalization.variant_group
                        writer:    pim_connector.writer.database.variant_group
                    parameters:
                        batchSize: 1
        csv_category_import:
            type:  import
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.csv_category
                        processor: pim_connector.processor.denormalization.category
                        writer:    pim_connector.writer.database.category
                    parameters:
                        batchSize: 1

        csv_category_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.category
                        processor: pim_connector.processor.normalization.category
                        writer:    pim_connector.writer.file.csv_category
        csv_attribute_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.attribute
                        processor: pim_connector.processor.normalization.attribute
                        writer:    pim_connector.writer.file.csv_attribute
        csv_attribute_option_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.attribute_option
                        processor: pim_connector.processor.normalization.attribute_option
                        writer:    pim_connector.writer.file.csv_attribute_option
        csv_association_type_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.association_type
                        processor: pim_connector.processor.normalization.association_type
                        writer:    pim_connector.writer.file.csv_association_type
        csv_group_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.group
                        processor: pim_connector.processor.normalization.group
                        writer:    pim_connector.writer.file.csv_group
        csv_variant_group_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.variant_group
                        processor: pim_connector.processor.normalization.variant_group
                        writer:    pim_connector.writer.file.csv_variant_group
        csv_family_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.family
                        processor: pim_connector.processor.normalization.family
                        writer:    pim_connector.writer.file.csv_family
