connector:
    name: Akeneo XLSX Connector
    jobs:
        xlsx_category_import:
            type:  import
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.xlsx_category
                        processor: pim_connector.processor.denormalization.category
                        writer:    pim_connector.writer.database.category
                    parameters:
                        batchSize: 1
        xlsx_variant_group_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.variant_group
                        processor: pim_connector.processor.normalization.variant_group
                        writer:    pim_connector.writer.file.xlsx_variant_group
                    parameters:
                        batch_size: 10
        xlsx_variant_group_import:
            type:  import
            steps:
                validation:
                    class: '%pim_connector.step.validator.class%'
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    services:
                        reader:    pim_connector.reader.file.xlsx_variant_group
                        processor: pim_connector.processor.denormalization.variant_group
                        writer:    pim_connector.writer.database.variant_group
                    parameters:
                        batchSize: 1
        xlsx_family_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.family
                        processor: pim_connector.processor.normalization.family
                        writer:    pim_connector.writer.file.xlsx_family
                    parameters:
                        batch_size: 10
        xlsx_category_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.category
                        processor: pim_connector.processor.normalization.category
                        writer:    pim_connector.writer.file.xlsx_category
                    parameters:
                        batch_size: 10
        xlsx_attribute_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.attribute
                        processor: pim_connector.processor.normalization.attribute
                        writer:    pim_connector.writer.file.xlsx_attribute
                    parameters:
                        batch_size: 10
        xlsx_attribute_option_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.attribute_option
                        processor: pim_connector.processor.normalization.attribute_option
                        writer:    pim_connector.writer.file.xlsx_attribute_option
                    parameters:
                        batch_size: 10
        xlsx_association_type_export:
            type:  export
            steps:
                export:
                    services:
                        reader:    pim_connector.reader.database.association_type
                        processor: pim_connector.processor.normalization.association_type
                        writer:    pim_connector.writer.file.xlsx_association_type
                    parameters:
                        batch_size: 10
