services:

    pim_enrich.controller.rest.locale:
        class: 'Akeneo\Channel\Bundle\Controller\InternalApi\LocaleController'
        arguments:
            - '@pim_catalog.repository.locale'
            - '@pim_internal_api_serializer'
            - '@pim_catalog.filter.chained'
