parameters:
    pim_enrich.view_element.tab.category_property.template:  'PimEnrichBundle:CategoryTree:Tab/property.html.twig'
    pim_enrich.view_element.tab.category_history.template:   'PimEnrichBundle:CategoryTree:Tab/history.html.twig'

services:
    pim_enrich.view_element.tab.category_property:
        parent: pim_enrich.view_element.tab.base
        arguments:
            - %pim_enrich.view_element.tab.category_property.template%
            - 'tab.pim_enrich_category_edit.property'
        tags:
            - { name: pim_enrich_view_element.tab, position: 90, identifier: pim_enrich_category_edit}

    pim_enrich.view_element.tab.category_history:
        parent: pim_enrich.view_element.tab.base
        arguments:
            - %pim_enrich.view_element.tab.category_history.template%
            - 'tab.pim_enrich_category_edit.history'
        calls:
            - [addVisibilityChecker, [@pim_enrich.view_element.visibility_checker.form_edit]]
        tags:
            - { name: pim_enrich_view_element.tab, position: 110, identifier: pim_enrich_category_edit}
