parameters:
    pim_datagrid.controller.datagrid.class:      Pim\Bundle\DataGridBundle\Controller\DatagridController
    pim_datagrid.controller.export.class:        Pim\Bundle\DataGridBundle\Controller\ExportController
    pim_datagrid.controller.datagrid_view.class: Pim\Bundle\DataGridBundle\Controller\DatagridViewController

services:
    pim_datagrid.controller.datagrid:
        scope: request
        class: %pim_datagrid.controller.datagrid.class%
        arguments:
            - '@templating'

    pim_datagrid.controller.export:
        class: %pim_datagrid.controller.export.class%
        arguments:
            - '@oro_datagrid.datagrid.manager'
            - '@oro_datagrid.mass_action.parameters_parser'
            - '@oro_datagrid.mass_action.dispatcher'
            - '@pim_serializer'
            - '@pim_catalog.manager.product'
            - '@pim_user.context.user'

    pim_datagrid.controller.datagrid_view:
        scope: request
        class: %pim_datagrid.controller.datagrid_view.class%
        parent: pim_enrich.controller.abstract_doctrine
        arguments:
            - '@pim_datagrid.manager.datagrid_view'
