parameters:
    pim_datagrid.datasource.orm.class:     Pim\Bundle\DataGridBundle\Datasource\Orm\OrmDatasource
    pim_datagrid.datasource.product.class: Pim\Bundle\DataGridBundle\Datasource\ProductDatasource
    pim_datagrid.datasource.adapter_resolver.class: Pim\Bundle\DataGridBundle\Datasource\DatasourceAdapterResolver

services:
    # TODO: change pim_catalog to pim_datagrid
    pim_catalog.datasource.orm:
        class: %pim_datagrid.datasource.orm.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_security.acl_helper'
            - '@pim_datagrid.datasource.result_record.hydrator.default'
        tags:
            - { name: oro_datagrid.datasource, type: pim_orm }

    pim_catalog.datasource.product:
        class: %pim_datagrid.datasource.product.class%
        arguments:
            - '@pim_catalog.object_manager.product'
            - '@pim_datagrid.datasource.result_record.hydrator.product'
            - '@pim_catalog.repository.product_mass_action'
        tags:
            - { name: oro_datagrid.datasource, type: pim_product }

    pim_datagrid.datasource.adapter_resolver:
        class: %pim_datagrid.datasource.adapter_resolver.class%
        arguments:
            - %pim_catalog.storage_driver%
            - %pim_filter.datasource.orm_adapter.class%
