parameters:
    pim_datagrid.extension.filter.class:                Pim\Bundle\DataGridBundle\Extension\Filter\FilterExtension
    pim_datagrid.extension.sorter.class:     Pim\Bundle\DataGridBundle\Extension\Sorter\SorterExtension
    pim_datagrid.extension.pager.orm_pager.class:       Pim\Bundle\DataGridBundle\Extension\Pager\OrmPagerExtension
    pim_datagrid.extension.pager.product_pager.class:   Pim\Bundle\DataGridBundle\Extension\Pager\ProductPagerExtension
    pim_datagrid.extension.selector.orm_selector.class: Pim\Bundle\DataGridBundle\Extension\Selector\OrmSelectorExtension

services:
    pim_datagrid.extension.filter:
        class: %pim_datagrid.extension.filter.class%
        arguments:
            - '@oro_datagrid.datagrid.request_params'
            - '@translator'
            - '@pim_datagrid.datasource.adapter_resolver'
        tags:
             - { name: oro_datagrid.extension }

    pim_datagrid.extension.sorter:
        class: %pim_datagrid.extension.sorter.class%
        arguments:
            - '@oro_datagrid.datagrid.request_params'
        tags:
            - { name: oro_datagrid.extension }

    pim_datagrid.extension.pager.orm_pager:
        class: %pim_datagrid.extension.pager.orm_pager.class%
        arguments:
            - '@pim_datagrid.extension.pager.orm.pager'
            - '@oro_datagrid.datagrid.request_params'
        tags:
            - { name: oro_datagrid.extension }

    pim_datagrid.extension.pager.product_pager:
        class: %pim_datagrid.extension.pager.product_pager.class%
        arguments:
            - '@pim_datagrid.extension.pager.product.pager'
            - '@oro_datagrid.datagrid.request_params'
        tags:
            - { name: oro_datagrid.extension }

    pim_datagrid.extension.selector.orm_selector:
        class: %pim_datagrid.extension.selector.orm_selector.class%
        arguments:
            - '@oro_datagrid.datagrid.request_params'
        tags:
             - { name: oro_datagrid.extension }
