parameters:
    pim_datagrid.extension.action.type.tab_redirect.class:     Pim\Bundle\DataGridBundle\Extension\Action\Actions\TabRedirectAction
    pim_datagrid.extension.export_action.handler.export.class: Pim\Bundle\DataGridBundle\Extension\ExportAction\ExportActionHandler
    pim_datagrid.extension.export_action.type.export.class:    Pim\Bundle\DataGridBundle\Extension\ExportAction\Actions\ExportAction

services:
    pim_datagrid.extension.action.type.tab_redirect:
        class: %pim_datagrid.extension.action.type.tab_redirect.class%
        scope: prototype
        tags:
            - { name: oro_datagrid.extension.action.type, type: tab-redirect }

    pim_datagrid.extension.export_action.handler.export:
        class: %pim_datagrid.extension.export_action.handler.export.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @pim_serializer

    pim_datagrid.extension.export_action.type.export:
        class: %pim_datagrid.extension.export_action.type.export.class%
        scope: prototype
        tags:
            - { name: pim_datagrid.extension.export_action.type, type: export }
