parameters:
    pim_datagrid.extension.filter.orm_filter.class: Pim\Bundle\DataGridBundle\Extension\Filter\OrmFilterExtension
    pim_datagrid.extension.sorter.orm_sorter.class: Pim\Bundle\DataGridBundle\Extension\Sorter\OrmSorterExtension
    pim_datagrid.extension.pager.orm_pager.class:   Pim\Bundle\DataGridBundle\Extension\Pager\OrmPagerExtension

services:
    pim_datagrid.extension.filter.orm_filter:
        class: %pim_datagrid.extension.filter.orm_filter.class%
        arguments:
            - @oro_datagrid.datagrid.request_params
            - @translator
        tags:
             - { name: oro_datagrid.extension }

    pim_datagrid.extension.sorter.orm_sorter:
        class: "%pim_datagrid.extension.sorter.orm_sorter.class%"
        arguments:
            - @oro_datagrid.datagrid.request_params
        tags:
            - { name: oro_datagrid.extension }

    pim_datagrid.extension.pager.orm_pager:
        class: "%pim_datagrid.extension.pager.orm_pager.class%"
        arguments:
            - @oro_datagrid.extension.pager.orm.pager
            - @oro_datagrid.datagrid.request_params
        tags:
            - { name: oro_datagrid.extension }
