parameters:
    pim_datagrid.datasource.result_record.hydrator.default.class: Pim\Bundle\DataGridBundle\Datasource\ResultRecord\Orm\ResultRecordHydrator

services:
    pim_datagrid.datasource.result_record.hydrator.product:
        class: %pim_datagrid.datasource.result_record.hydrator.product.class%

    pim_datagrid.datasource.result_record.hydrator.object_id:
        class: %pim_datagrid.datasource.result_record.hydrator.object_id.class%

    pim_datagrid.datasource.result_record.hydrator.object:
        class: %pim_datagrid.datasource.result_record.hydrator.object.class%

    pim_datagrid.datasource.result_record.hydrator.default:
        class: %pim_datagrid.datasource.result_record.hydrator.default.class%
