parameters:
    pim_datagrid.mass_action.dispatcher.class:               Pim\Bundle\DataGridBundle\Extension\MassAction\MassActionDispatcher
    pim_datagrid.extension.mass_action.handler.export.class: Pim\Bundle\DataGridBundle\Extension\MassAction\Actions\Export\ExportMassActionHandler
    pim_datagrid.extension.mass_action.type.export.class:    Pim\Bundle\DataGridBundle\Extension\MassAction\Actions\Export\ExportMassAction

services:
    oro_datagrid.mass_action.dispatcher:
        class: %pim_datagrid.mass_action.dispatcher.class%
        arguments:
            - '@service_container'
            - '@oro_datagrid.datagrid.manager'
            - '@oro_datagrid.datagrid.request_params'

    pim_datagrid.extension.mass_action.handler.export:
        class: %pim_datagrid.extension.mass_action.handler.export.class%

    pim_datagrid.extension.mass_action.type.export:
        class: %pim_datagrid.extension.mass_action.type.export.class%
        scope: prototype
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: export }
