parameters:
    pim_datagrid.extension.selector.orm.flexible_values_selector.class:  Pim\Bundle\DataGridBundle\Extension\Selector\Orm\FlexibleValuesSelector
    pim_datagrid.extension.selector.orm.flexible_option_selector.class:  Pim\Bundle\DataGridBundle\Extension\Selector\Orm\FlexibleOptionSelector
    pim_datagrid.extension.selector.orm.flexible_options_selector.class: Pim\Bundle\DataGridBundle\Extension\Selector\Orm\FlexibleOptionsSelector
    pim_datagrid.extension.selector.orm.flexible_prices_selector.class:  Pim\Bundle\DataGridBundle\Extension\Selector\Orm\FlexiblePricesSelector
    pim_datagrid.extension.selector.orm.flexible_metric_selector.class:  Pim\Bundle\DataGridBundle\Extension\Selector\Orm\FlexibleMetricSelector
    pim_datagrid.extension.selector.orm.flexible_media_selector.class:   Pim\Bundle\DataGridBundle\Extension\Selector\Orm\FlexibleMediaSelector

services:
    pim_datagrid.extension.selector.orm.flexible_values_selector:
        class: %pim_datagrid.extension.selector.orm.flexible_values_selector.class%
        tags:
            - { name: pim_datagrid.extension.selector, type: flexible_values }

    pim_datagrid.extension.selector.orm.flexible_option_selector:
        class: %pim_datagrid.extension.selector.orm.flexible_option_selector.class%
        arguments:
            - '@pim_datagrid.extension.selector.orm.flexible_values_selector'
        tags:
            - { name: pim_datagrid.extension.selector, type: flexible_option }

    pim_datagrid.extension.selector.orm.flexible_options_selector:
        class: %pim_datagrid.extension.selector.orm.flexible_options_selector.class%
        arguments:
            - '@pim_datagrid.extension.selector.orm.flexible_values_selector'
        tags:
            - { name: pim_datagrid.extension.selector, type: flexible_options }

    pim_datagrid.extension.selector.orm.flexible_prices_selector:
        class: %pim_datagrid.extension.selector.orm.flexible_prices_selector.class%
        arguments:
            - '@pim_datagrid.extension.selector.orm.flexible_values_selector'
        tags:
            - { name: pim_datagrid.extension.selector, type: flexible_price }

    pim_datagrid.extension.selector.orm.flexible_metric_selector:
        class: %pim_datagrid.extension.selector.orm.flexible_metric_selector.class%
        arguments:
            - '@pim_datagrid.extension.selector.orm.flexible_values_selector'
        tags:
            - { name: pim_datagrid.extension.selector, type: flexible_metric }

    pim_datagrid.extension.selector.orm.flexible_media_selector:
        class: %pim_datagrid.extension.selector.orm.flexible_media_selector.class%
        arguments:
            - '@pim_datagrid.extension.selector.orm.flexible_values_selector'
        tags:
            - { name: pim_datagrid.extension.selector, type: flexible_media }
