assetic:
    bundles:
        - OroAsseticBundle
        - OroUIBundle
        - OroUserBundle
        - OroFilterBundle
        - OroNavigationBundle
        - OroWindowsBundle
        - OroEntityExtendBundle
        - OroSecurityBundle
        - PimUIBundle
        - PimCatalogBundle
        - PimEnrichBundle
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: \.less$
