oro_user:
    email:
        address: %mailer_from_address%
        name:    %mailer_from_name%
    privileges:
        entity:
            label: rights.entity
            view_type: grid
            types: [entity]
            field_type: pim_acl_access_level_selector
            fix_values: false
            default_value: 5
            show_default: true
        action:
            label: rights.action
            view_type: groups
            types: [action]
            field_type: pim_acl_access_level_selector
            fix_values: false
            default_value: 5
            show_default: true
