parameters:
    pim_notification.event_subscriber.job_execution_notifier.class: Pim\Bundle\NotificationBundle\EventSubscriber\JobExecutionNotifier

services:
    pim_notification.event_subscriber.job_execution_notifier:
        class: %pim_notification.event_subscriber.job_execution_notifier.class%
        arguments:
            - '@pim_notification.manager.user_notification'
#            - '@pim_import_export.repository.job_execution'
        tags:
            - { name: kernel.event_subscriber }
