parameters:
    pim_notification.factory.notification.class: Pim\Bundle\NotificationBundle\Factory\NotificationFactory

services:
    pim_notification.factory.notification:
        class: %pim_notification.factory.notification.class%
