parameters:
    pim_notification.manager.notification.class: Pim\Bundle\NotificationBundle\Manager\NotificationManager

services:
    pim_notification.manager.notification:
        class: %pim_notification.manager.notification.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_notification.repository.notification'
            - '@pim_notification.factory.notification'
            - '@oro_user.manager'
