parameters:
    pim_notification.repository.notification.class: Pim\Bundle\NotificationBundle\Entity\Repository\NotificationRepository

services:
    pim_notification.repository.notification:
        class: %pim_notification.repository.notification.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_notification.entity.notification.class%]
        tags:
            - { name: 'pim_repository' }
