pim_notification_notification_list:
    path: /notification/list
    defaults: { _controller: pim_notification.controller.notification:listAction, _format: html }

pim_notification_notification_mark_viewed:
    path: /notification/mark_viewed/{id}
    defaults: { _controller: pim_notification.controller.notification:markAsViewedAction, _format: html }
    requirements:
        id: all|\d+

pim_notification_notification_remove:
    path: /notification/remove/{id}
    defaults: { _controller: pim_notification.controller.notification:removeAction, _format: html }
    requirements:
        id: \d+
