pim_notification_notification_list:
    path: /notification/list/{id}
    defaults: { _controller: pim_notification.controller.notification:listAction, _format: html }
    requirements:
        userId: \d+

pim_notification_notification_mark_viewed:
    path: /notification/mark_viewed/{userId}/{ids}
    defaults: { _controller: pim_notification.controller.notification:markAsViewedAction, _format: html }
    requirements:
        userId: \d+
        ids: all|\d+
