parameters:
    pim_connector.akeneo_batch.command.class: Pim\Bundle\ConnectorBundle\Command\BatchCommand

services:
    pim_connector.akeneo_batch.command:
        class: '%pim_connector.akeneo_batch.command.class%'
        arguments:
            - '@monolog.logger.batch'
            - '@akeneo_batch.logger.batch_log_handler'
            - '@akeneo_batch.job.job_instance_repository'
            - '@doctrine'
            - '@validator'
            - '@akeneo_batch.mail_notifier'
            - '@akeneo_batch.job_parameters_factory'
            - '@akeneo_batch.job.job_parameters_validator'
            - '@akeneo_batch.job.job_registry'
            - '@akeneo_batch.job_repository'
            - '@pim_user.provider.user'
            - '@security.token_storage'
        tags:
            - { name: console.command }
