parameters:
    pim_connector.reader.dummy_item.class: Pim\Component\Connector\Reader\DummyItemReader

    pim_connector.reader.database.product.class: Pim\Component\Connector\Reader\Database\ProductReader
    pim_connector.reader.database.base.class:    Pim\Component\Connector\Reader\Database\BaseReader

    pim_connector.reader.file.csv.class:               Pim\Component\Connector\Reader\File\CsvReader
    pim_connector.reader.file.csv_variant_group.class: Pim\Component\Connector\Reader\File\CsvVariantGroupReader
    pim_connector.reader.file.csv_association.class:   Pim\Component\Connector\Reader\File\CsvAssociationReader
    pim_connector.reader.file.csv_product.class:       Pim\Component\Connector\Reader\File\Product\CsvProductReader

    pim_connector.reader.file.xlsx.class:         Pim\Component\Connector\Reader\File\XlsxReader
    pim_connector.reader.file.xlsx_product.class: Pim\Component\Connector\Reader\File\Product\XlsxProductReader

    pim_connector.reader.file.file_iterator.class:          Pim\Component\Connector\Reader\File\FileIterator
    pim_connector.reader.file.file_iterator_factory.class:  Pim\Component\Connector\Reader\File\FileIteratorFactory
    pim_connector.reader.file.media_path_transformer.class: Pim\Component\Connector\Reader\File\Product\MediaPathTransformer

services:
    pim_connector.reader.database.product:
        class: '%pim_connector.reader.database.product.class%'
        arguments:
            - '@pim_catalog.query.product_query_builder_factory'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.manager.completeness'
            - '@pim_catalog.converter.metric'
            - '@akeneo_storage_utils.doctrine.object_detacher'
            - '@akeneo_batch.job_repository'
            - true

    pim_connector.reader.file.csv_iterator_factory:
        class: '%pim_connector.reader.file.file_iterator_factory.class%'
        arguments:
            - '%pim_connector.reader.file.file_iterator.class%'
            - 'csv'

    pim_connector.reader.file.xlsx_iterator_factory:
        class: '%pim_connector.reader.file.file_iterator_factory.class%'
        arguments:
            - '%pim_connector.reader.file.file_iterator.class%'
            - 'xlsx'

    pim_connector.reader.file.media_path_transformer:
        class: '%pim_connector.reader.file.media_path_transformer.class%'
        arguments:
            - '@pim_catalog.repository.attribute'

    # Dummy Reader
    pim_connector.reader.dummy_item:
        class: '%pim_connector.reader.dummy_item.class%'

    # CSV File Readers
    pim_connector.reader.file.csv:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_dummy_convertor_to_move'

    pim_connector.reader.file.csv_association_type:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.association_type'

    pim_connector.reader.file.csv_family:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.family'

    pim_connector.reader.file.csv_association:
        class: '%pim_connector.reader.file.csv_association.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.product_association'

    pim_connector.reader.file.csv_attribute:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.attribute'

    pim_connector.reader.file.csv_attribute_option:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.attribute_option'

    pim_connector.reader.file.csv_group:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.group'

    pim_connector.reader.file.csv_variant_group:
        class: '%pim_connector.reader.file.csv_variant_group.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.variant_group'
            - '@pim_connector.reader.file.media_path_transformer'

    pim_connector.reader.file.csv_category:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.category'

    pim_connector.reader.file.csv_channel:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.channel'

    pim_connector.reader.file.csv_locale:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.locale'

    pim_connector.reader.file.csv_attribute_group:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.attribute_group'

    pim_connector.reader.file.csv_group_type:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.group_type'

    pim_connector.reader.file.csv_currency:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.currency'

    pim_connector.reader.file.csv_product:
        class: '%pim_connector.reader.file.csv_product.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.product'
            - '@pim_connector.reader.file.media_path_transformer'

    pim_connector.reader.file.csv_user:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.user'

    pim_connector.reader.file.csv_user_group:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.user_group'

    pim_connector.reader.file.csv_user_role:
        class: '%pim_connector.reader.file.csv.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.user_role'

    # XLSX file Readers
    pim_connector.reader.file.xlsx:
        class: '%pim_connector.reader.file.xlsx.class%'
        arguments:
            - '@pim_connector.reader.file.xlsx_iterator_factory'
            - '@pim_dummy_convertor_to_move'

    pim_connector.reader.file.xlsx_product:
       class: '%pim_connector.reader.file.xlsx_product.class%'
       arguments:
           - '@pim_connector.reader.file.xlsx_iterator_factory'
           - '@pim_connector.array_converter.flat_to_standard.product'
           - '@pim_connector.reader.file.media_path_transformer'

    pim_connector.reader.file.xlsx_association_type:
        class: '%pim_connector.reader.file.xlsx.class%'
        arguments:
            - '@pim_connector.reader.file.xlsx_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.association_type'

    pim_connector.reader.file.xlsx_association:
        class: '%pim_connector.reader.file.xlsx.class%'
        arguments:
            - '@pim_connector.reader.file.xlsx_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.product_association'

    pim_connector.reader.file.xlsx_group:
        class: '%pim_connector.reader.file.xlsx.class%'
        arguments:
            - '@pim_connector.reader.file.xlsx_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.group'

    pim_connector.reader.file.xlsx_variant_group:
        class: '%pim_connector.reader.file.xlsx.class%'
        arguments:
            - '@pim_connector.reader.file.xlsx_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.variant_group'

    pim_connector.reader.file.xlsx_attribute:
        class: '%pim_connector.reader.file.xlsx.class%'
        arguments:
            - '@pim_connector.reader.file.xlsx_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.attribute'

    pim_connector.reader.file.xlsx_attribute_option:
        class: '%pim_connector.reader.file.xlsx.class%'
        arguments:
            - '@pim_connector.reader.file.xlsx_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.attribute_option'

    pim_connector.reader.file.xlsx_family:
        class: '%pim_connector.reader.file.xlsx.class%'
        arguments:
            - '@pim_connector.reader.file.xlsx_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.family'

    pim_connector.reader.file.xlsx_category:
        class: '%pim_connector.reader.file.xlsx.class%'
        arguments:
            - '@pim_connector.reader.file.xlsx_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.category'
