parameters:
    # Encoder
    pim_serializer.encoder.csv.class: Pim\Component\Connector\Encoder\CsvEncoder


services:
    # Encoder
    pim_serializer.encoder.csv:
        public: false
        class: '%pim_serializer.encoder.csv.class%'
        tags:
            - { name: pim_serializer.encoder, priority: 90 }

    pim_connector.processor.csv_serializer:
        abstract: true
        arguments:
            - '@pim_serializer'
            - '@pim_catalog.repository.locale'
