parameters:
    # Encoder
    pim_serializer.encoder.csv.class: Pim\Component\Connector\Encoder\CsvEncoder


services:
    # Encoder
    pim_serializer.encoder.csv:
        public: false
        class: '%pim_serializer.encoder.csv.class%'
        tags:
            - { name: pim_serializer.encoder, priority: 90 }
