parameters:
    pim_base_connector.writer.doctrine.base.class: Pim\Component\Connector\Writer\Doctrine\BaseWriter

services:
    pim_base_connector.writer.doctrine.attribute_option:
        class: %pim_base_connector.writer.doctrine.base.class%
        arguments:
            - '@pim_catalog.saver.attribute_option'
            - '@akeneo_storage_utils.doctrine.object_detacher'
