parameters:
    pim_datagrid.datasource.product.result_record.hydrator.class: Pim\Bundle\DataGridBundle\Datasource\ResultRecord\MongoDbOdm\ProductHydrator
    pim_datagrid.datasource.result_record.hydrator.object_id.class: Pim\Bundle\DataGridBundle\Datasource\ResultRecord\MongoDbOdm\ObjectIdHydrator
    pim_filter.datasource.product_adapter.class:                  Pim\Bundle\FilterBundle\Datasource\MongoDbOdm\OdmFilterDatasourceAdapter
    pim_datagrid.extension.pager.product.pager.class:             Pim\Bundle\DataGridBundle\Extension\Pager\MongoDbOdm\Pager

services: ~
