extensions:
    pim-job-instance-csv-base-import-show:
        module: pim/form/common/edit-form

    pim-job-instance-csv-base-import-show-mainImage:
        module: pim/form/common/main-image
        parent: pim-job-instance-csv-base-import-show
        targetZone: main-image
        config:
            # TODO It's not the right path. Wait for @yulldesign to have right one.
            path: bundles/pimui/images/icon-download-purple.svg

    pim-job-instance-csv-base-import-show-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-job-instance-csv-base-import-show
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    pim-job-instance-csv-base-import-show-subsection:
        module: pim/form/common/subsection
        parent: pim-job-instance-csv-base-import-show
        targetZone: content
        config:
            title: pim_enrich.form.job_instance.subsection.last_executions

    pim-job-instance-csv-base-import-show-grid:
        module: pim/job/common/grid
        parent: pim-job-instance-csv-base-import-show-subsection
        position: 1000
        targetZone: content
        config:
            alias: last-import-executions-grid
            metadata:
                jobType: import

    pim-job-instance-csv-base-import-show-upload:
        module: pim/job/common/edit/upload
        parent: pim-job-instance-csv-base-import-show
        aclResourceId: pim_importexport_import_profile_launch
        targetZone: content
        position: 90

    pim-job-instance-csv-base-import-show-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-csv-base-import-show
        targetZone: title
        position: 100

    pim-job-instance-csv-base-import-show-edit:
        module: pim/common/redirect
        parent: pim-job-instance-csv-base-import-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_import_profile_edit
            identifier:
                path: code
                name: code

    pim-job-instance-csv-base-import-show-launch:
        module: pim/job/common/edit/upload-launch
        parent: pim-job-instance-csv-base-import-show
        aclResourceId: pim_importexport_import_profile_launch
        targetZone: buttons
        position: 110
        config:
            launch: pim_enrich.form.job_instance.button.import.launch
            upload: pim_enrich.form.job_instance.button.import.upload
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code
