extensions:
    pim-job-instance-xlsx-product-export-show:
        module: pim/form/common/edit-form

    pim-job-instance-xlsx-product-export-show-main-image:
        module: pim/form/common/main-image
        parent: pim-job-instance-xlsx-product-export-show
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustration-export-xlsx.svg

    pim-job-instance-xlsx-product-export-show-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-job-instance-xlsx-product-export-show
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-job-instance-xlsx-product-export-show-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-job-instance-xlsx-product-export-show
        targetZone: breadcrumbs
        config:
            tab: pim-menu-exports

    pim-job-instance-xlsx-product-export-show-launch:
        module: pim/job/common/edit/launch
        parent: pim-job-instance-xlsx-product-export-show
        targetZone: meta
        position: 110
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: true

    pim-job-instance-xlsx-product-export-show-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-xlsx-product-export-show-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.file_path.help

    pim-job-instance-csv-product-export-show-properties-decimal-separator:
        module: pim/job/common/edit/field/decimal-separator
        parent: pim-job-instance-csv-product-export-show-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.decimalSeparator
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.decimal_separator.title
            tooltip: pim_enrich.form.job_instance.tab.properties.decimal_separator.help

    pim-job-instance-xlsx-product-export-show-properties-date-format:
        module: pim/job/product/edit/field/date-format
        parent: pim-job-instance-xlsx-product-export-show-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.dateFormat
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.date_format.title
            tooltip: pim_enrich.form.job_instance.tab.properties.date_format.help

    pim-job-instance-xlsx-product-export-show-properties-lines-per-file:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-xlsx-product-export-show-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.linesPerFile
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.lines_per_file.title
            tooltip: pim_enrich.form.job_instance.tab.properties.lines_per_file.help

    pim-job-instance-xlsx-product-export-show-properties-with-header:
        module: pim/job/common/edit/field/switch
        parent: pim-job-instance-xlsx-product-export-show-properties
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.withHeader
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.with_header.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_header.help

    pim-job-instance-xlsx-product-export-show-properties-with-media:
        module: pim/job/common/edit/field/switch
        parent: pim-job-instance-xlsx-product-export-show-properties
        position: 170
        targetZone: global-settings
        config:
            fieldCode: configuration.with_media
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.with_media.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_media.help

    pim-job-instance-xlsx-product-export-show-content-structure:
        module: pim/job/product/edit/content/structure
        parent: pim-job-instance-xlsx-product-export-show-content
        targetZone: structure-filters
        position: 100

    pim-job-instance-xlsx-product-export-show-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-xlsx-product-export-show
        targetZone: title
        position: 100

    pim-job-instance-xlsx-product-export-show-edit:
        module: pim/common/redirect
        parent: pim-job-instance-xlsx-product-export-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_export_profile_edit
            buttonClass: AknButton AknButton--action
            identifier:
                path: code
                name: code

    pim-job-instance-xlsx-product-export-show-subsection:
        module: pim/form/common/subsection
        parent: pim-job-instance-xlsx-product-export-show
        targetZone: content
        config:
            title: pim_enrich.form.job_instance.subsection.last_executions

    pim-job-instance-xlsx-product-export-show-grid:
        module: pim/job/common/grid
        parent: pim-job-instance-xlsx-product-export-show-subsection
        position: 1000
        targetZone: content
        config:
            alias: last-export-executions-grid
            metadata:
                jobType: export
