extensions:
    pim-job-instance-yml-base-import-show:
        module: pim/form/common/edit-form

    pim-job-instance-yml-base-import-show-mainImage:
        module: pim/form/common/main-image
        parent: pim-job-instance-yml-base-import-show
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustration-import-yml.svg

    pim-job-instance-yml-base-import-show-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-job-instance-yml-base-import-show
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    pim-job-instance-yml-base-import-show-switcher:
        module: pim/job-instance/import/switcher
        parent: pim-job-instance-yml-base-import-show
        position: 0
        targetZone: meta

    pim-job-instance-yml-base-import-show-launch-switcher-item:
        module: pim/job-instance/import/switcher-item
        parent: pim-job-instance-yml-base-import-show
        targetZone: content
        aclResourceId: pim_importexport_import_profile_launch
        position: 40
        config:
            label: IMPORT NOW

    pim-job-instance-yml-base-import-show-launch:
        module: pim/job/common/edit/upload-launch
        parent: pim-job-instance-yml-base-import-show-launch-switcher-item
        config:
            launch: pim_enrich.form.job_instance.button.import.launch
            upload: pim_enrich.form.job_instance.button.import.upload
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code

    pim-job-instance-yml-base-import-show-upload-switcher-item:
        module: pim/job-instance/import/switcher-item
        parent: pim-job-instance-yml-base-import-show
        targetZone: content
        aclResourceId: pim_importexport_import_profile_launch
        position: 50
        config:
            label: UPLOAD

    pim-job-instance-yml-base-import-show-upload:
        module: pim/job/common/edit/upload
        parent: pim-job-instance-yml-base-import-show-upload-switcher-item

    pim-job-instance-yml-base-import-show-subsection:
        module: pim/form/common/subsection
        parent: pim-job-instance-yml-base-import-show
        targetZone: content
        config:
            title: pim_enrich.form.job_instance.subsection.last_executions

    pim-job-instance-yml-base-import-show-grid:
        module: pim/job/common/grid
        parent: pim-job-instance-yml-base-import-show-subsection
        position: 1000
        targetZone: content
        config:
            alias: last-import-executions-grid
            metadata:
                jobType: import

    pim-job-instance-yml-base-import-show-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-yml-base-import-show
        targetZone: title
        position: 100

    pim-job-instance-yml-base-import-show-edit:
        module: pim/common/redirect
        parent: pim-job-instance-yml-base-import-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_import_profile_edit
            identifier:
                path: code
                name: code
