parameters:
    pim_ui.repository.notification.class: Pim\Bundle\UIBundle\Entity\Repository\NotificationRepository

services:
    pim_ui.repository.notification:
        class: %pim_ui.repository.notification.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_ui.entity.notification.class%]
        tags:
            - { name: 'pim_repository' }
