config:
    shim:
        jquery-ui:
            deps:
                - jquery
        jquery-ui-timepicker:
            deps:
                - jquery-ui
        jquery.numeric:
            deps:
                - jquery
        jquery.select2:
            deps:
                - jquery
        jquery.jstree:
            deps:
                - jquery
        jstree/jquery.hotkeys:
            deps:
                - jquery.jstree
        bootstrap:
            deps:
                - jquery
        bootstrap-tooltip:
            deps:
                - bootstrap
        underscore:
            exports: _
        backbone:
            deps:
                - jquery
                - underscore
            exports: Backbone
        backbone/bootstrap-modal:
            deps:
                - jquery
                - underscore
                - backbone
        jquery-ui-full:
            deps:
                - jquery
        jquery.slimbox:
            deps:
                - jquery
        bootstrap.bootstrapswitch:
            deps:
                - jquery
        jquery.sidebarize:
            deps:
                - jquery
    map:
        '*':
            jquery: oro/jquery-setup
            jquery-ui: oro/jquery-ui-datepicker-l10n
            jquery-ui-timepicker: oro/jquery-ui-timepicker-l10n
        oro/jquery-setup:
            jquery: jquery
        oro/jquery-ui-datepicker-l10n:
            jquery-ui: jquery-ui
        oro/jquery-ui-timepicker-l10n:
            jquery-ui-timepicker: jquery-ui-timepicker

    paths:
        text:                          pimui/lib/text
        json:                          pimui/lib/json2
        base64:                        pimui/lib/base64
        jquery:                        pimui/lib/jquery-1.10.2
        jquery-ui:                     pimui/lib/jquery-ui.min
        jquery-ui-timepicker:          pimui/lib/jquery-ui-timepicker-addon
        jquery.numeric:                pimui/lib/jquery/jquery.numeric
        jquery.select2:                pimui/lib/jquery/select2
        jquery.jstree:                 pimui/lib/jstree/jquery.jstree
        jstree/jquery.hotkeys:         pimui/lib/jstree/jquery.hotkeys
        bootstrap:                     pimui/lib/bootstrap.min
        bootstrap-tooltip:             pimui/lib/bootstrap/js/bootstrap-tooltip
        underscore:                    pimui/lib/underscore
        backbone:                      pimui/lib/backbone
        backbone/bootstrap-modal:      pimui/lib/backbone.bootstrap-modal
        oro/app:                       pimui/js/app
        oro/error:                     pimui/js/error
        oro/init-layout:               pimui/js/init-layout
        oro/jquery-setup:              pimui/js/jquery-setup
        oro/jquery-ui-datepicker-l10n: pimui/js/jquery-ui-datepicker-l10n
        oro/jquery-ui-timepicker-l10n: pimui/js/jquery-ui-timepicker-l10n
        oro/layout:                    pimui/js/layout
        oro/mediator:                  pimui/js/mediator
        oro/messenger:                 pimui/js/messenger
        oro/modal:                     pimui/js/modal
        oro/delete-confirmation:       pimui/js/delete-confirmation
        oro/tools:                     pimui/js/tools

        oro/form/state:                pimui/js/form/state.js

        jquery-ui-full:            pimui/lib/jquery/jquery-ui-1.10.3.custom.min
        jquery.slimbox:            pimui/js/slimbox2
        bootstrap.bootstrapswitch: pimui/lib/bootstrap/js/bootstrap.switch
        tinymce:                   pimui/lib/tinymce/tinymce.min
        wysiwyg:                   pimui/js/pim-wysiwyg
        datepicker:                pimui/js/pim-datepicker
        jquery.sidebarize:         pimui/js/jquery.sidebarize
        pim/ui:                    pimui/js/pim-ui
        pim/initselect2:           pimui/js/pim-initselect2
        pim/dialog:                pimui/js/pim-dialog
        pim/formupdatelistener:    pimui/js/pim-formupdatelistener
        pim/saveformstate:         pimui/js/pim-saveformstate
        pim/fileinput:             pimui/js/pim-fileinput
        pim/dialogform:            pimui/js/pim-dialogform
