parameters:
    pim_enrich.mass_edit.temporary_file.cleaner.class: Pim\Bundle\EnrichBundle\MassEditAction\Cleaner\MassEditTemporaryFileCleaner

services:
    pim_enrich.mass_edit.temporary_file.cleaner:
        class: %pim_enrich.mass_edit.temporary_file.cleaner.class%
        arguments:
            - '@pim_catalog.updater.product'
            - '@pim_validator'
            - '@pim_catalog.repository.product_mass_action'
            - '@pim_catalog.repository.attribute'
