parameters:
    pim_enrich.colors:
        navy:    '0,31,63,.4'
        blue:    '0,116,217,.4'
        aqua:    '127,219,255,.4'
        teal:    '57,204,204,.4'
        olive:   '61,153,112,.4'
        green:   '46,204,64,.4'
        lime:    '1,255,112,.4'
        yellow:  '255,220,0,.4'
        orange:  '255,133,27,.4'
        red:     '255,65,54,.4'
        maroon:  '133,20,75,.4'
        fuchsia: '240,18,190,.4'
        purple:  '177,13,201,.4'
        white:   '255,255,255,.4'
        silver:  '221,221,221,.4'
        gray:    '170,170,170,.4'
        black:   '17,17,17,.4'
