extensions:
    product-edit-form:
        module: pim/product-edit-form
        zones:
            header: >div>header
            title: header .product-title
            buttons: header .actions
            meta: header .meta
            state: header .state

    sequential-edit:
        module: pim/product-edit-form/sequential-edit
        parent: product-edit-form
        insertAction: before
        targetZone: header

    form-tabs:
        module: pim/product-edit-form/form-tabs
        parent: product-edit-form
        targetZone: header
        insertAction: after
        zones:
            container: .tab-container

    product-label:
        module: pim/product-edit-form/product-label
        parent: product-edit-form
        targetZone: title

    back-to-grid:
        module: pim/product-edit-form/back-to-grid
        parent: product-edit-form
        targetZone: buttons
        aclResourceId: pim_enrich_product_index

    download-pdf:
        module: pim/product-edit-form/download-pdf
        parent: product-edit-form
        targetZone: buttons
        aclResourceId: pim_pdf_generator_product_download

    status-switcher:
        module: pim/product-edit-form/status-switcher
        parent: product-edit-form
        targetZone: buttons
        aclResourceId: pim_enrich_product_change_state

    delete:
        module: pim/product-edit-form/delete
        parent: product-edit-form
        targetZone: buttons
        aclResourceId: pim_enrich_product_remove

    save-buttons:
        module: pim/product-edit-form/save-buttons
        parent: product-edit-form
        targetZone: buttons

    save:
        module: pim/product-edit-form/save
        parent: product-edit-form
        targetZone: buttons

    state:
        module: pim/product-edit-form/state
        parent: product-edit-form
        insertAction: append
        targetZone: state

    family:
        module: pim/product-edit-form/meta/family
        parent: product-edit-form
        targetZone: meta
        zones:
            family: self

    change-family:
        module: pim/product-edit-form/meta/change-family
        parent: family
        insertAction: append
        targetZone: family
        aclResourceId: pim_enrich_product_change_family

    groups:
        module: pim/product-edit-form/meta/groups
        parent: product-edit-form
        insertAction: append
        targetZone: meta

    created:
        module: pim/product-edit-form/meta/created
        parent: product-edit-form
        insertAction: append
        targetZone: meta

    updated:
        module: pim/product-edit-form/meta/updated
        parent: product-edit-form
        insertAction: append
        targetZone: meta

    attributes:
        module: pim/product-edit-form/attributes
        parent: form-tabs
        targetZone: container
        aclResourceId: pim_enrich_product_edit_attributes
        zones:
            header: .tab-content > header
            edit-actions: .tab-content > header > .attribute-edit-actions
            context-selectors: .tab-content > header > .attribute-edit-actions > .context-selectors
            other-actions: .tab-content > header > .attribute-edit-actions > .other-actions
            attributes: self

    categories:
        module: pim/product-edit-form/categories
        parent: form-tabs
        targetZone: container
        aclResourceId: pim_enrich_product_categories_view
        zones:
            categories: self

    associations:
        module: pim/product-edit-form/associations
        parent: form-tabs
        targetZone: container
        aclResourceId: pim_enrich_associations_view
        zones:
            header: .tab-content > header
            associations: self

    panels:
        module: pim/product-edit-form/panel/panels
        parent: form-tabs
        targetZone: container
        insertAction: after
        zones:
            panel-content: .panel-content

    attribute-group-selector:
        module: pim/product-edit-form/attributes/attribute-group-selector
        parent: attributes
        targetZone: attributes
        insertAction: prepend

    add-attribute:
        module: pim/product-edit-form/attributes/add-attribute
        parent: attributes
        targetZone: other-actions
        insertAction: append
        aclResourceId: pim_enrich_product_add_attribute

    scope-switcher:
        module: pim/product-edit-form/scope-switcher
        parent: attributes
        targetZone: context-selectors
        insertAction: append

    locale-switcher:
        module: pim/product-edit-form/locale-switcher
        parent: attributes
        targetZone: context-selectors
        insertAction: append

    copy:
        module: pim/product-edit-form/attributes/copy
        parent: attributes
        targetZone: header
        zones:
            copy-actions: .other-actions > .copy-actions
            context-selectors: .context-selectors
            other-actions: .other-actions

    validation:
        module: pim/product-edit-form/attributes/validation
        parent: attributes
        targetZone: header

    variant-group:
        module: pim/product-edit-form/attributes/variant-group
        parent: attributes
        targetZone: attributes

    completeness:
        parent: panels
        module: pim/product-edit-form/panel/completeness
        targetZone: panel-content
        insertAction: append

    comments:
        parent: panels
        module: pim/product-edit-form/panel/comments
        targetZone: panel-content
        insertAction: append
        aclResourceId: pim_enrich_product_comment

    history:
        parent: panels
        module: pim/product-edit-form/panel/history
        targetZone: panel-content
        insertAction: append
        aclResourceId: pim_enrich_product_history
        zones:
            history: self

    selector:
        parent: panels
        module: pim/product-edit-form/panel/selector

    copy-scope-switcher:
        module: pim/product-edit-form/scope-switcher
        parent: copy
        targetZone: context-selectors
        insertAction: append

    copy-locale-switcher:
        module: pim/product-edit-form/locale-switcher
        parent: copy
        targetZone: context-selectors
        insertAction: append

attribute_fields:
    pim_catalog_boolean:          pim/boolean-field
    pim_catalog_date:             pim/date-field
    pim_catalog_file:             pim/media-field
    pim_catalog_image:            pim/media-field
    pim_catalog_metric:           pim/metric-field
    pim_catalog_multiselect:      pim/multi-select-field
    pim_catalog_number:           pim/number-field
    pim_catalog_price_collection: pim/price-collection-field
    pim_catalog_simpleselect:     pim/simple-select-field
    pim_catalog_identifier:       pim/text-field
    pim_catalog_text:             pim/text-field
    pim_catalog_textarea:         pim/textarea-field
