parameters:
    pim_enrich.generator.product_pdf.class: Pim\Bundle\EnrichBundle\Generator\ProductPdfGenerator
    pim_enrich.generator.pdf_registry.class: Pim\Bundle\EnrichBundle\Generator\PdfGeneratorRegistry

services:
    pim_enrich.generator.product_pdf:
        class: %pim_enrich.generator.product_pdf.class%
        arguments:
            - '@templating'
            - 'PimEnrichBundle:Product:generatePdf.html.twig'
        tags:
            - { name: pim_enrich.pdf_generator, priority: 80 }

    pim_enrich.generator.pdf_registry:
        class: %pim_enrich.generator.pdf_registry.class%
