oro_menu_config:
    items:
        home:
            name: Home
            label: ''
            extras:
                icon: icon-home
                position: 1
            route: oro_default
        pim_enrich_tab:
            label: pim_menu.tab.enrich
            uri: '#'
            extras:
                position: 20
            showNonAuthorized: false
        pim_enrich_product:
            label: pim_menu.item.product
            route: pim_enrich_product_index
            aclResourceId: pim_enrich_product_index
        pim_enrich_attribute:
            label: pim_menu.item.attribute
            route: pim_enrich_attribute_index
            aclResourceId: pim_enrich_attribute_index
        pim_enrich_family:
            label: pim_menu.item.family
            route: pim_enrich_family_index
            aclResourceId: pim_enrich_family_index
        pim_enrich_attributegroup:
            label: pim_menu.item.attribute_group
            route: pim_enrich_attributegroup_create
            aclResourceId: pim_enrich_attribute_group_create
        pim_enrich_categorytree:
            label: pim_menu.item.category
            route: pim_enrich_categorytree_create
            aclResourceId: pim_enrich_category_create
        pim_import_tab:
            label: pim_menu.tab.collect
            uri: '#'
            extras:
                position: 10
            showNonAuthorized: false
        pim_export_tab:
            label: pim_menu.tab.spread
            uri: '#'
            extras:
                position: 30
            showNonAuthorized: false
        pim_configuration_tab:
            label: pim_menu.tab.settings
            uri: '#'
            extras:
                position: 50
            showNonAuthorized: false
        system_tab:
            extras:
                position: 60
            showNonAuthorized: false
        pim_enrich_locale:
            label: pim_menu.item.locale
            route: pim_enrich_locale_index
            aclResourceId: pim_enrich_locale_index
        pim_enrich_currency:
            label: pim_menu.item.currency
            route: pim_enrich_currency_index
            aclResourceId: pim_enrich_currency_index
        pim_enrich_channel:
            label: pim_menu.item.channel
            route: pim_enrich_channel_index
            aclResourceId: pim_enrich_channel_index
        pim_enrich_variant_group:
            label: pim_menu.item.variant_group
            route: pim_enrich_variant_group_index
            aclResourceId: pim_enrich_group_index
        pim_enrich_group:
            label: pim_menu.item.group
            route: pim_enrich_group_index
            aclResourceId: pim_enrich_group_index
        pim_enrich_association_type:
            label: pim_menu.item.association_type
            route: pim_enrich_association_type_index
            aclResourceId: pim_enrich_association_type_index
        pim_enrich_group_type:
            label: pim_menu.item.group_type
            route: pim_enrich_group_type_index
            aclResourceId: pim_enrich_group_type_index

        oro_tag_list:
            display: false
        oro_business_unit_list:
            display: false
        oro_email_emailtemplate_list:
            display: false
        emails:
            display: false
        oro_notification_emailnotification_list:
            display: false
        entities_list:
            display: false
        oro_cron_job:
            display: false
        system_configuraion:
            display: false
        oro_calendar_view_default:
            display: false

    tree:
        application_menu:
            children:
                pim_enrich_tab:
                    children:
                        pim_enrich_product: ~
                        pim_enrich_categorytree: ~
                        pim_enrich_variant_group: ~
                        pim_enrich_group: ~

                pim_configuration_tab:
                    children:
                        pim_enrich_attributegroup: ~
                        pim_enrich_attribute: ~
                        pim_enrich_family: ~
                        pim_enrich_association_type: ~
                        pim_enrich_group_type: ~
                        pim_enrich_currency: ~
                        pim_enrich_locale: ~

                pim_export_tab:
                    children:
                        pim_enrich_channel: ~

oro_titles:
    oro_default:                         Dashboard
    pim_enrich_attributegroup_create:   Attribute groups | Create
    pim_enrich_attributegroup_edit:     Attribute groups %%group.label%% | Edit
    pim_enrich_categorytree_listtree:   Category trees | List
    pim_enrich_categorytree_create:     Category trees | Create
    pim_enrich_categorytree_edit:       Category trees %%category.label%% | Edit
    pim_enrich_attribute_index:         Attributes
    pim_enrich_attribute_create:        Attributes | Create
    pim_enrich_attribute_edit:          Attributes %%attribute.label%% | Edit
    pim_enrich_product_index:           Products
    pim_enrich_product_create:          Products | Create
    pim_enrich_product_edit:            Products %%product.sku%% | Edit
    pim_enrich_family_index:            Families
    pim_enrich_family_create:           Families | Create
    pim_enrich_family_edit:             Families %%family.label%% | Edit
    pim_enrich_channel_index:           Channels
    pim_enrich_channel_create:          Channels | Create
    pim_enrich_channel_edit:            Channels %%channel.label%% | Edit
    pim_enrich_currency_index:          Currencies
    pim_enrich_locale_index:            Locales
    pim_enrich_locale_edit:             Locales %%locale.code%% | Edit
    pim_enrich_group_index:             Groups
    pim_enrich_group_create:            Groups | Create
    pim_enrich_group_edit:              Groups %%group.label%% | Edit
    pim_enrich_variant_group_index:     Variant groups
    pim_enrich_variant_group_create:    Variant groups | Create
    pim_enrich_variant_group_edit:      Variant groups %%group.label%% | Edit
    pim_enrich_association_type_index:  Association types
    pim_enrich_association_type_create: Association types | Create
    pim_enrich_association_type_edit:   Association types %%association type.label%% | Edit
    pim_enrich_group_type_index:        Group types
    pim_enrich_group_type_create:       Group types | Create
    pim_enrich_group_type_edit:         Group types %%group type.label%% | Edit
