parameters:
    pim_enrich.normalizer.attribute_option_value_collection.class: Pim\Bundle\EnrichBundle\Normalizer\AttributeOptionValueCollectionNormalizer
    pim_enrich.normalizer.attribute_option.class:                  Pim\Bundle\EnrichBundle\Normalizer\AttributeOptionNormalizer
    pim_enrich.normalizer.attribute_option_value.class:            Pim\Bundle\EnrichBundle\Normalizer\AttributeOptionValueNormalizer
    pim_enrich.normalizer.product.class:                           Pim\Bundle\EnrichBundle\Normalizer\ProductNormalizer
    pim_enrich.normalizer.completeness.class:                      Pim\Bundle\EnrichBundle\Normalizer\CompletenessNormalizer
    pim_enrich.normalizer.completeness_collection.class:           Pim\Bundle\EnrichBundle\Normalizer\CompletenessCollectionNormalizer
    pim_enrich.normalizer.version.class:                           Pim\Bundle\EnrichBundle\Normalizer\VersionNormalizer
    pim_enrich.normalizer.collection.class:                        Pim\Bundle\EnrichBundle\Normalizer\CollectionNormalizer

services:
   pim_enrich.normalizer.attribute_option_value_collection:
        class: %pim_enrich.normalizer.attribute_option_value_collection.class%
        tags:
            - { name: pim_internal_api_serializer.normalizer }

   pim_enrich.normalizer.attribute_option:
        class: %pim_enrich.normalizer.attribute_option.class%
        arguments:
            - '@pim_catalog.manager.locale'
            - '@pim_catalog.manager.attribute_option'
        tags:
            - { name: pim_internal_api_serializer.normalizer }

   pim_enrich.normalizer.attribute_option_value:
        class: %pim_enrich.normalizer.attribute_option_value.class%
        tags:
            - { name: pim_internal_api_serializer.normalizer }

   pim_enrich.normalizer.product:
        class: %pim_enrich.normalizer.product.class%
        arguments:
            - '@pim_serializer.normalizer.product'
            - '@pim_versioning.manager.version'
        tags:
            - { name: pim_internal_api_serializer.normalizer }

   pim_enrich.normalizer.completeness:
        class: %pim_enrich.normalizer.completeness.class%
        tags:
            - { name: pim_internal_api_serializer.normalizer }

   pim_enrich.normalizer.completeness_collection:
        class: %pim_enrich.normalizer.completeness_collection.class%
        arguments:
            - '@pim_internal_api_serializer'

   pim_enrich.normalizer.version:
        class: %pim_enrich.normalizer.version.class%
        tags:
            - { name: pim_internal_api_serializer.normalizer }

   pim_enrich.normalizer.collection:
        class: %pim_enrich.normalizer.collection.class%
        tags:
            - { name: pim_internal_api_serializer.normalizer }
