parameters:
    pim_enrich.renderer.product_pdf.class: Pim\Bundle\EnrichBundle\Renderer\ProductPdfRenderer
    pim_enrich.renderer.registry.class: Pim\Bundle\EnrichBundle\Renderer\RendererRegistry
    pim_enrich.renderer.dompdf_builder.class: Pim\Bundle\EnrichBundle\Renderer\PdfBuilder\DompdfBuilder

services:
    pim_enrich.renderer.product_pdf:
        class: %pim_enrich.renderer.product_pdf.class%
        arguments:
            - '@templating'
            - 'PimEnrichBundle:Product:renderPdf.html.twig'
            - '@pim_enrich.renderer.pdf_builder'
        tags:
            - { name: pim_enrich.renderer, priority: 80 }

    pim_enrich.renderer.registry:
        class: %pim_enrich.renderer.registry.class%

    pim_enrich.renderer.pdf_builder:
        class: %pim_enrich.renderer.dompdf_builder.class%
        arguments:
            - '@slik_dompdf'
