parameters:
    ## Searchable repositories
    pim_enrich.repository.family.search.class:           Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\FamilySearchableRepository
    pim_enrich.repository.family_variant.search.class:   Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\FamilyVariantSearchableRepository

    ## Default UI repositories
    pim_enrich.repository.category.class:                Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\CategoryRepository
    pim_enrich.repository.group.class:                   Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\GroupRepository
    pim_enrich.repository.group_type.class:              Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\GroupTypeRepository
    pim_enrich.repository.association_type.class:        Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\AssociationTypeRepository
    pim_enrich.repository.family_variant.class:          Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\FamilyVariantRepository
    pim_enrich.repository.locale.class:                  Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\LocaleRepository
    pim_enrich.repository.channel.class:                 Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\ChannelRepository
    pim_enrich.repository.currency.class:                Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\CurrencyRepository
    pim_enrich.repository.job_instance.class:            Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\JobInstanceRepository
    pim_enrich.repository.job_execution.class:           Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\JobExecutionRepository
    pim_enrich.repository.job_tracker.class:             Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\JobTrackerRepository
    pim_enrich.repository.client.class:                  Pim\Bundle\EnrichBundle\Doctrine\ORM\Repository\ClientRepository

services:
    ## Searchable repositories
    pim_enrich.repository.family.search:
        class: '%pim_enrich.repository.family.search.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.family.class%'

    pim_enrich.repository.family_variant.search:
        class: '%pim_enrich.repository.family_variant.search.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.family_variant.class%'

    ## Default UI repositories
    pim_enrich.repository.category:
        class: '%pim_enrich.repository.category.class%'
        arguments:
            - '@pim_user.context.user'
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.category.class%'

    pim_enrich.repository.group:
        class: '%pim_enrich.repository.group.class%'
        arguments:
            - '@pim_user.context.user'
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.group.class%'

    pim_enrich.repository.group_type:
        class: '%pim_enrich.repository.group_type.class%'
        arguments:
            - '@pim_user.context.user'
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.group_type.class%'

    pim_enrich.repository.association_type:
        class: '%pim_enrich.repository.association_type.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.association_type.class%'

    pim_enrich.repository.family_variant:
        class: '%pim_enrich.repository.family_variant.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.family_variant.class%'

    pim_enrich.repository.locale:
        class: '%pim_enrich.repository.locale.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.locale.class%'

    pim_enrich.repository.channel:
        class: '%pim_enrich.repository.channel.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.channel.class%'

    pim_enrich.repository.currency:
        class: '%pim_enrich.repository.currency.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.currency.class%'

    pim_enrich.repository.job_instance:
        class: '%pim_enrich.repository.job_instance.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%akeneo_batch.entity.job_instance.class%'

    pim_enrich.repository.job_execution:
        class: '%pim_enrich.repository.job_execution.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%akeneo_batch.entity.job_execution.class%'

    pim_enrich.repository.job_tracker:
        class: '%pim_enrich.repository.job_tracker.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%akeneo_batch.entity.job_execution.class%'

    pim_enrich.repository.client:
        class: '%pim_enrich.repository.client.class%'
        arguments:
            - '@fos_oauth_server.entity_manager'
            - '%fos_oauth_server.model.client.class%'
