config:
    shim:
        jquery.wizard:
            deps:
                - jquery
        jstree/jquery.jstree.tree_selector:
            deps:
                - jquery.jstree
        jstree/nested_switch:
            deps:
                - jquery.jstree

    paths:
        jquery.wizard:                      pimenrich/js/jquery.wizard
        jstree/jquery.jstree.tree_selector: pimenrich/js/jstree/jquery.jstree.tree_selector
        jstree/nested_switch:               pimenrich/js/jstree/jquery.jstree.nested_switch
        pim/init:                           pimenrich/js/pim-init
        pim/asynctab:                       pimenrich/js/pim-async-tab
        pim/popinform:                      pimenrich/js/pim-popinform
        pim/optionform:                     pimenrich/js/pim-optionform
        pim/scopable:                       pimenrich/js/pim-scopable
        pim/currencyfield:                  pimenrich/js/pim-currencyfield
        pim/tree/view:                      pimenrich/js/tree-view.jstree
        pim/tree/associate:                 pimenrich/js/tree-associate.jstree
        pim/tree/manage:                    pimenrich/js/tree-manage.jstree
        pim/attributeoptionview:            pimenrich/js/pim-attributeoptionview
        pim/item/tableview:                 pimenrich/js/pim-item-tableview
        pim/item/view:                      pimenrich/js/pim-item-view
        pim/product-edit-form:              pimenrich/js/product/edit-form
        pim/field-manager:                  pimenrich/js/product/field-manager
        pim/attribute-manager:              pimenrich/js/product/attribute-manager
        pim/attribute-group-manager:        pimenrich/js/product/attribute-group-manager
        pim/config-manager:                 pimenrich/js/product/config-manager
        pim/variant-group-manager:                 pimenrich/js/product/variant-group-manager

        # Fields
        pim/field:                          pimenrich/js/product/field/field
        pim/boolean-field:                  pimenrich/js/product/field/boolean-field
        pim/date-field:                     pimenrich/js/product/field/date-field
        pim/media-field:                    pimenrich/js/product/field/media-field
        pim/metric-field:                   pimenrich/js/product/field/metric-field
        pim/multi-select-field:             pimenrich/js/product/field/multi-select-field
        pim/number-field:                   pimenrich/js/product/field/number-field
        pim/price-collection-field:         pimenrich/js/product/field/price-collection-field
        pim/simple-select-field:            pimenrich/js/product/field/simple-select-field
        pim/text-field:                     pimenrich/js/product/field/text-field
        pim/textarea-field:                     pimenrich/js/product/field/textarea-field

        # Templates
        pim/template/product/form:                   pimenrich/templates/product/form.html
        pim/template/product/field/field:          pimenrich/templates/product/field/field.html
        pim/template/product/field/boolean:          pimenrich/templates/product/field/boolean.html
        pim/template/product/field/date:             pimenrich/templates/product/field/date.html
        pim/template/product/field/media:            pimenrich/templates/product/field/media.html
        pim/template/product/field/metric:           pimenrich/templates/product/field/metric.html
        pim/template/product/field/multi-select:     pimenrich/templates/product/field/multi-select.html
        pim/template/product/field/number:           pimenrich/templates/product/field/number.html
        pim/template/product/field/price-collection: pimenrich/templates/product/field/price-collection.html
        pim/template/product/field/simple-select:    pimenrich/templates/product/field/simple-select.html
        pim/template/product/field/text:             pimenrich/templates/product/field/text.html
        pim/template/product/field/textarea:         pimenrich/templates/product/field/textarea.html
