parameters:
    pim_enrich.imagine.loader.flysystem.class: Pim\Bundle\EnrichBundle\Imagine\Loader\FlysystemLoader

services:
    pim_enrich.imagine.loader.flysystem:
        class: %pim_enrich.imagine.loader.flysystem.class%
        arguments:
            - '@oneup_flysystem.mount_manager'
            - 'storage'
        tags:
            - { name: liip_imagine.binary.loader, loader: flysystem_data_loader }

#    acme.s3_client:
#        class: Aws\S3\S3Client
#        factory_class: Aws\S3\S3Client
#        factory_method: factory
#        arguments:
#            -
#                key: 'key'
#                secret: 'secret'
#                region: 'region'
