parameters:
    pim_enrich.imagine.loader.flysystem.class: Pim\Bundle\EnrichBundle\Imagine\Loader\FlysystemLoader

services:
    pim_enrich.imagine.loader.flysystem:
        class: %pim_enrich.imagine.loader.flysystem.class%
        arguments:
            - '@akeneo_file_storage.file_storage.filesystem_provider'
            - ['catalogStorage']
        tags:
            - { name: liip_imagine.binary.loader, loader: flysystem_data_loader }
