services:
    pim_enrich.saver.mass_edit.configuration:
        class:  %pim_catalog.saver.base.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.saver.base_options_resolver'
            - %pim_base_connector.entity.job_configuration.class%
