%pim_catalog.entity.category.class%:
    alias:                          pim_category
    title_fields:                   [label]
    route:
        name:                       pim_enrich_categorytree_edit
        parameters:
            id:                     id
    search_template:                PimEnrichBundle:CategoryTree:result.html.twig
    fields:
        -
            name:                   label
            target_type:            text
            target_fields:          [label]
        -
            name:                   code
            target_type:            text
            target_fields:          [code]

%pim_catalog.entity.product.class%:
    alias:                          pim_product
    route:
        name:                       pim_enrich_product_edit
        parameters:
            id:                     id
    search_template:                PimEnrichBundle:Product:result.html.twig
    fields:
        -
            name: values
            relation_type: one-to-many
            relation_fields:
                -
                    name: varchar
                    target_type: text
                    target_fields: [all_text]
                -
                    name: text
                    target_type: text
                    target_fields: [all_text]
