parameters:
    pim_base_connector.reader.doctrine.product_reader.class: Pim\Bundle\BaseConnectorBundle\Reader\Doctrine\ORMProductReader

services:
    pim_base_connector.reader.doctrine.product_reader:
        class: %pim_base_connector.reader.doctrine.product_reader.class%
        arguments:
            - '@pim_catalog.repository.product'
            - '@pim_catalog.manager.channel'
            - '@pim_catalog.manager.completeness'
            - '@pim_transform.converter.metric'
            - '@pim_catalog.object_manager.product'