pim_api_attribute_group_list:
    path: /attribute-groups
    defaults: { _controller: pim_api.controller.attribute_group:listAction, _format: json }
    methods: [GET]

pim_api_attribute_group_get:
    path: /attribute-groups/{code}
    defaults: { _controller: pim_api.controller.attribute_group:getAction, _format: json }
    methods: [GET]
