pim_api_product_list:
    path: /products
    defaults: { _controller: pim_api.controller.product:listAction, _format: json }
    methods: [GET]

pim_api_product_get:
    path: /products/{code}
    defaults: { _controller: pim_api.controller.product:getAction, _format: json }
    methods: [GET]

pim_api_product_create:
    path: /products
    defaults: { _controller: pim_api.controller.product:createAction, _format: json }
    methods: [POST]

pim_api_product_partial_update:
    path: /products/{code}
    defaults: { _controller: pim_api.controller.product:partialUpdateAction, _format: json }
    methods: [PATCH]

pim_api_proposal_partial_update:
    path: /proposals/{code}
    defaults: { _controller: pim_api.controller.proposal:partialUpdateAction, _format: json }
    methods: [PATCH]

pim_api_product_partial_update_list:
    path: /products
    defaults: { _controller: pim_api.controller.product:partialUpdateListAction, _format: json }
    methods: [PATCH]

pim_api_product_delete:
    path: /products/{code}
    defaults: { _controller: pim_api.controller.product:deleteAction, _format: json }
    methods: [DELETE]

pim_api_notification_list:
    path: /notification/list
    defaults: { _controller: pim_api.controller.notification:listAction, _format: json }

pim_api_notification_count_unread:
    path: /notification/count_unread
    defaults: { _controller: pim_api.controller.notification:countUnreadAction, _format: json }

pim_api_notification_mark_viewed:
    path: /notification/mark_viewed/{id}
    defaults: { _controller: pim_api.controller.notification:markAsViewedAction, _format: json, id: ~ }
    requirements:
        id: \d+
        _method: POST

pim_api_notification_remove:
    path: /notification/remove/{id}
    defaults: { _controller: pim_api.controller.notification:removeAction, _format: json }
    requirements:
        id: \d+
        _method: DELETE
