parameters:
    pim_serializer.normalizer.flat.association_type.class:  Pim\Bundle\VersioningBundle\Normalizer\Flat\AssociationTypeNormalizer
    pim_serializer.normalizer.flat.attribute.class:         Pim\Bundle\VersioningBundle\Normalizer\Flat\AttributeNormalizer
    pim_serializer.normalizer.flat.attribute_group.class:   Pim\Bundle\VersioningBundle\Normalizer\Flat\AttributeGroupNormalizer
    pim_serializer.normalizer.flat.category.class:          Pim\Bundle\VersioningBundle\Normalizer\Flat\CategoryNormalizer
    pim_serializer.normalizer.flat.channel.class:           Pim\Bundle\VersioningBundle\Normalizer\Flat\ChannelNormalizer
    pim_serializer.normalizer.flat.family.class:            Pim\Bundle\VersioningBundle\Normalizer\Flat\FamilyNormalizer
    pim_serializer.normalizer.flat.group.class:             Pim\Bundle\VersioningBundle\Normalizer\Flat\GroupNormalizer
    pim_serializer.normalizer.flat.job_instance.class:      Pim\Bundle\VersioningBundle\Normalizer\Flat\JobInstanceNormalizer
    pim_serializer.normalizer.flat.label_translation.class: Pim\Bundle\VersioningBundle\Normalizer\Flat\TranslationNormalizer
    pim_serializer.normalizer.flat.product.class:           Pim\Bundle\VersioningBundle\Normalizer\Flat\ProductNormalizer
    pim_serializer.normalizer.flat.product_value.class:     Pim\Bundle\VersioningBundle\Normalizer\Flat\ProductValueNormalizer
    pim_serializer.normalizer.flat.locale.class:            Pim\Bundle\VersioningBundle\Normalizer\Flat\LocaleNormalizer

    pim_serializer.normalizer.flat.collection.class:        Pim\Bundle\VersioningBundle\Normalizer\Flat\CollectionNormalizer
    pim_serializer.normalizer.flat.datetime.class:          Pim\Bundle\VersioningBundle\Normalizer\Flat\DateTimeNormalizer
    pim_serializer.normalizer.flat.metric.class:            Pim\Bundle\VersioningBundle\Normalizer\Flat\MetricNormalizer
    pim_serializer.normalizer.flat.option.class:            Pim\Bundle\VersioningBundle\Normalizer\Flat\AttributeOptionNormalizer
    pim_serializer.normalizer.flat.price.class:             Pim\Bundle\VersioningBundle\Normalizer\Flat\PriceNormalizer
    pim_serializer.normalizer.flat.file.class:              Pim\Bundle\VersioningBundle\Normalizer\Flat\FileNormalizer

services:
    pim_versioning.serializer.normalizer.flat.product:
        public: false
        class: '%pim_serializer.normalizer.flat.product.class%'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.product_value:
        public: false
        class: '%pim_serializer.normalizer.flat.product_value.class%'
        arguments:
            - '@pim_catalog.localization.localizer.registry'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.category:
        class: '%pim_serializer.normalizer.flat.category.class%'
        arguments:
            - '@pim_serializer.normalizer.flat.label_translation'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.attribute:
        class: '%pim_serializer.normalizer.flat.attribute.class%'
        arguments:
            - '@pim_serializer.normalizer.flat.label_translation'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.family:
        class: '%pim_serializer.normalizer.flat.family.class%'
        arguments:
            - '@pim_serializer.normalizer.flat.label_translation'
            - '@pim_catalog.filter.chained'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.attribute_requirement'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.attribute_group:
        class: '%pim_serializer.normalizer.flat.attribute_group.class%'
        arguments:
            - '@pim_serializer.normalizer.flat.label_translation'
            - '@pim_catalog.repository.attribute'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.association_type:
        class: '%pim_serializer.normalizer.flat.association_type.class%'
        arguments:
            - '@pim_serializer.normalizer.flat.label_translation'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.group:
        class: '%pim_serializer.normalizer.flat.group.class%'
        arguments:
            - '@pim_serializer.normalizer.flat.label_translation'
            - '@pim_serializer.denormalizer.product_values'
            - '@pim_serializer.normalizer.product_values'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.job_instance:
        class: '%pim_serializer.normalizer.flat.job_instance.class%'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.channel:
        class: '%pim_serializer.normalizer.flat.channel.class%'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.label_translation:
        class: '%pim_serializer.normalizer.flat.label_translation.class%'
        parent: pim_serializer.normalizer.label_translation
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.collection:
        class: '%pim_serializer.normalizer.flat.collection.class%'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.datetime:
        class: '%pim_serializer.normalizer.flat.datetime.class%'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.metric:
        class: '%pim_serializer.normalizer.flat.metric.class%'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.option:
        class: '%pim_serializer.normalizer.flat.option.class%'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.price:
        class: '%pim_serializer.normalizer.flat.price.class%'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.file:
        class: '%pim_serializer.normalizer.flat.file.class%'
        arguments:
            - '@pim_connector.writer.file.media_exporter_path_generator'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.locale:
        class: '%pim_serializer.normalizer.flat.locale.class%'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }
