Pim\Component\Catalog\Model\VariantProduct:
    type: entity
    manyToOne:
        productModel:
            targetEntity: Pim\Component\Catalog\Model\ProductModelInterface
            joinColumns:
                product_model_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
