services:
    ### External API
    pim_api.controller.attribute:
        class: 'Akeneo\Pim\Structure\Bundle\Controller\ExternalApi\AttributeController'
        arguments:
            - '@pim_api.repository.attribute'
            - '@pim_serializer'
            - '@pim_catalog.factory.attribute'
            - '@pim_catalog.updater.attribute'
            - '@validator'
            - '@pim_catalog.saver.attribute'
            - '@router'
            - '@pim_api.pagination.offset_hal_paginator'
            - '@pim_api.pagination.parameter_validator'
            - '@pim_api.stream.attribute_partial_update_stream'
            - '%pim_api.configuration%'

    pim_api.controller.attribute_group:
        class: 'Akeneo\Pim\Structure\Bundle\Controller\ExternalApi\AttributeGroupController'
        arguments:
            - '@pim_api.repository.attribute_group'
            - '@pim_serializer'
            - '@pim_api.pagination.parameter_validator'
            - '@pim_api.pagination.offset_hal_paginator'
            - '@pim_catalog.factory.attribute_group'
            - '@pim_catalog.updater.attribute_group'
            - '@validator'
            - '@router'
            - '@pim_catalog.saver.attribute_group'
            - '@pim_api.stream.attribute_group_partial_update_stream'
            - '%pim_api.configuration%'

    pim_api.controller.attribute_option:
        class: 'Akeneo\Pim\Structure\Bundle\Controller\ExternalApi\AttributeOptionController'
        arguments:
            - '@pim_api.repository.attribute'
            - '@pim_api.repository.attribute_option'
            - '@pim_serializer'
            - '@pim_catalog.factory.attribute_option'
            - '@pim_catalog.updater.attribute_option'
            - '@validator'
            - '@pim_catalog.saver.attribute_option'
            - '@router'
            - '@pim_api.pagination.offset_hal_paginator'
            - '@pim_api.pagination.parameter_validator'
            - '@pim_api.stream.attribute_option_partial_update_stream'
            - '%pim_api.configuration%'
            - ['pim_catalog_simpleselect', 'pim_catalog_multiselect']

    pim_api.controller.family:
        class: 'Akeneo\Pim\Structure\Bundle\Controller\ExternalApi\FamilyController'
        arguments:
            - '@pim_api.repository.family'
            - '@pim_serializer'
            - '@pim_catalog.factory.family'
            - '@pim_catalog.updater.family'
            - '@validator'
            - '@pim_catalog.saver.family'
            - '@router'
            - '@pim_api.pagination.offset_hal_paginator'
            - '@pim_api.pagination.parameter_validator'
            - '@pim_api.stream.family_partial_update_stream'
            - '%pim_api.configuration%'

    pim_api.controller.family_variant:
        class: 'Akeneo\Pim\Structure\Bundle\Controller\ExternalApi\FamilyVariantController'
        arguments:
            - '@pim_api.repository.family'
            - '@pim_api.repository.family_variant'
            - '@pim_serializer'
            - '@pim_api.pagination.offset_hal_paginator'
            - '@pim_api.pagination.parameter_validator'
            - '@validator'
            - '@pim_catalog.factory.family_variant'
            - '@pim_api.updater.family_variant'
            - '@pim_catalog.saver.family_variant'
            - '@router'
            - '@pim_api.stream.family_variant_partial_update_stream'
            - '%pim_api.configuration%'

    ### Internal Api
    pim_enrich.controller.rest.attribute:
        class: 'Akeneo\Pim\Structure\Bundle\Controller\InternalApi\AttributeController'
        arguments:
            - '@pim_catalog.repository.attribute'
            - '@pim_internal_api_serializer'
            - '@security.token_storage'
            - '@pim_catalog.filter.chained'
            - '@pim_enrich.repository.attribute.search'
            - '@pim_catalog.updater.attribute'
            - '@validator'
            - '@pim_catalog.saver.attribute'
            - '@pim_catalog.remover.attribute'
            - '@pim_catalog.factory.attribute'
            - '@pim_user.context.user'
            - '@pim_catalog.localization.localizer.number'
            - '@pim_enrich.normalizer.attribute'
            - '@translator'
            - '@pim_catalog.doctrine.query.attribute_is_an_family_variant_axis'

    pim_enrich.controller.rest.attribute_group:
        class: 'Akeneo\Pim\Structure\Bundle\Controller\InternalApi\AttributeGroupController'
        arguments:
            - '@pim_catalog.repository.attribute_group'
            - '@pim_enrich.repository.attribute_group.search'
            - '@pim_internal_api_serializer'
            - '@pim_catalog.filter.chained'
            - '@pim_catalog.updater.attribute_group'
            - '@validator'
            - '@pim_catalog.saver.attribute_group'
            - '@pim_catalog.remover.attribute_group'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.updater.attribute'
            - '@pim_catalog.saver.attribute'
            - '@oro_security.security_facade'
            - '@pim_catalog.factory.attribute_group'
            - '@event_dispatcher'
            - '@pim_catalog.filter.chained'
