services:
    ### Attribute
    pim_catalog.normalizer.standard.attribute:
        class: 'Akeneo\Pim\Structure\Component\Normalizer\Standard\AttributeNormalizer'
        arguments:
            - '@pim_catalog.normalizer.standard.translation'
            - '@pim_catalog.normalizer.standard.datetime'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_api.normalizer.attribute:
        class: 'Akeneo\Pim\Structure\Component\Normalizer\ExternalApi\AttributeNormalizer'
        arguments:
            - '@pim_catalog.normalizer.standard.attribute'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_enrich.normalizer.attribute:
        class: 'Akeneo\Pim\Structure\Component\Normalizer\InternalApi\AttributeNormalizer'
        arguments:
            - '@pim_serializer'
            - '@pim_enrich.provider.field.chained'
            - '@pim_enrich.provider.empty_value.chained'
            - '@pim_enrich.provider.filter.chained'
            - '@pim_catalog.localization.localizer.number'

    pim_versioning.serializer.normalizer.flat.attribute:
        class: 'Akeneo\Pim\Structure\Component\Normalizer\Versionning\AttributeNormalizer'
        arguments:
            - '@pim_catalog.normalizer.standard.attribute'
            - '@pim_versioning.serializer.normalizer.flat.label_translation'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    ### Attribute option
    pim_enrich.normalizer.attribute_option:
        class: 'Akeneo\Pim\Structure\Component\Normalizer\InternalApi\AttributeOptionNormalizer'
        arguments:
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.factory.attribute_option_value'
        tags:
            - { name: pim_internal_api_serializer.normalizer }

    pim_api.normalizer.attribute_option:
        class: 'Akeneo\Pim\Structure\Component\Normalizer\ExternalApi\AttributeOptionNormalizer'
        arguments:
            - '@pim_catalog.normalizer.standard.attribute_option'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_versioning.serializer.normalizer.flat.option:
        class: 'Akeneo\Pim\Structure\Component\Normalizer\Versionning\AttributeOptionNormalizer'
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 90 }

    pim_catalog.normalizer.standard.attribute_option:
        class: 'Akeneo\Pim\Structure\Component\Normalizer\Standard\AttributeOptionNormalizer'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
