services:
    pim_catalog.repository.attribute_group:
        class: 'Akeneo\Pim\Structure\Bundle\Doctrine\ORM\Repository\AttributeGroupRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.attribute_group.class%']
        tags:
            - { name: 'pim_repository' }

    pim_catalog.repository.attribute:
        class: 'Akeneo\Pim\Structure\Bundle\Doctrine\ORM\Repository\AttributeRepository'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.attribute.class%']
        tags:
            - { name: 'pim_repository' }
