### External Api
external_api_attribute:
    resource: '@AkeneoPimStructureBundle/Resources/config/routing/external_api/attribute.yml'
    prefix: /api/rest/v1

external_api_attribute_group:
    resource: '@AkeneoPimStructureBundle/Resources/config/routing/external_api/attribute_group.yml'
    prefix: /api/rest/v1

external_api_family:
    resource: '@AkeneoPimStructureBundle/Resources/config/routing/external_api/family.yml'
    prefix: /api/rest/v1

### Internal API
internal_api_attribute:
    resource: '@AkeneoPimStructureBundle/Resources/config/routing/internal_api/attribute.yml'
    prefix: /rest/attribute

internal_api_attribute_group:
    resource: '@AkeneoPimStructureBundle/Resources/config/routing/internal_api/attribute_group.yml'
    prefix: /rest/attribute-group

internal_api_family:
    resource: '@AkeneoPimStructureBundle/Resources/config/routing/internal_api/family.yml'
    prefix: /configuration/family

### Front routes
front_routes:
    resource: '@AkeneoPimStructureBundle/Resources/config/routing/front.yml'
