extensions:
    pim-export-execution-index:
        module: pim/common/simple-view
        config:
            template: pim/template/common/default-template

    pim-export-execution-index-grid-container:
        module: pim/common/simple-view
        parent: pim-export-execution-index
        targetZone: content
        config:
            template: pim/template/form/index/index

    pim-export-execution-index-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-export-execution-index
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-export-execution-index-grid-title:
        module: pim/common/grid-title
        parent: pim-export-execution-index
        targetZone: title
        config:
            title: pim_enrich.index.export_history.title
            countable: false

    pim-export-execution-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-export-execution-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-exports

    pim-export-execution-index-filters-list:
        module: oro/datafilter/filters-list
        parent: pim-export-execution-index-grid-container
        targetZone: filters

    pim-export-execution-index-filters-manage:
        module: oro/datafilter/filters-button
        parent: pim-export-execution-index-grid-container
        targetZone: filters

    pim-export-execution-index-pagination:
        module: oro/datagrid/pagination-input
        parent: pim-export-execution-index-grid-container
        targetZone: toolbar

    pim-export-execution-index-grid:
        module: pim/form/common/index/grid
        parent: pim-export-execution-index
        position: 1000
        targetZone: content
        config:
            alias: export-execution-grid
            metadata:
                jobType: export
