Akeneo\Pim\Structure\Component\Model\VariantAttributeSet:
    constraints:
        - Pim\Component\Catalog\Validator\Constraints\ImmutableVariantAxes: ~
    payload:
        standardPropertyName: variant_attribute_sets
