parameters:
    akeneo_doctrine_extensions.event_subscriber.mongodb.entities_type.class: Akeneo\Bundle\DoctrineExtensionsBundle\EventSubscriber\MongoDBODM\EntitiesTypeSubscriber
    akeneo_doctrine_extensions.event_subscriber.mongodb.entity_type.class:   Akeneo\Bundle\DoctrineExtensionsBundle\EventSubscriber\MongoDBODM\EntityTypeSubscriber
    akeneo_doctrine_extensions.mongodb.mongo_objects_factory.class:        Akeneo\Bundle\DoctrineExtensionsBundle\MongoDB\MongoObjectsFactory
    akeneo_doctrine_extensions.doctrine.smart_manager_registry.class:      Akeneo\Bundle\DoctrineExtensionsBundle\Doctrine\SmartManagerRegistry

services:
    akeneo_doctrine_extensions.event_subscriber.mongodb.resolve_target_repositories:
        class: %akeneo_doctrine_extensions.event_subscriber.resolve_target_repository.class%
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }

    akeneo_doctrine_extensions.event_subscriber.mongodb.entities_type:
        class: %akeneo_doctrine_extensions.event_subscriber.mongodb.entities_type.class%
        arguments:
            - '@akeneo_doctrine_extensions.factory.referenced_collection'
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }

    akeneo_doctrine_extensions.event_subscriber.mongodb.entity_type:
        class: %akeneo_doctrine_extensions.event_subscriber.mongodb.entity_type.class%
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }

    akeneo_doctrine_extensions.mongodb.mongo_objects_factory:
        class: %akeneo_doctrine_extensions.mongodb.mongo_objects_factory.class%

    akeneo_doctrine_extensions.doctrine.smart_manager_registry:
        class: %akeneo_doctrine_extensions.doctrine.smart_manager_registry.class%
        calls:
            - [addRegistry, ['@doctrine']]
            - [addRegistry, ['@doctrine_mongodb']]

