parameters:
    doctrine.entity_repository.class:   Doctrine\ORM\EntityRepository
    doctrine.document_repository.class: Doctrine\ODM\MongoDB\DocumentRepository
    pim_catalog.doctrine.smart_manager_registry.class: Akeneo\Bundle\DoctrineHybridSupportBundle\Doctrine\SmartManagerRegistry
    pim_catalog.doctrine.table_name_builder.class:     Akeneo\Bundle\DoctrineHybridSupportBundle\Doctrine\TableNameBuilder

services:
    pim_catalog.doctrine.smart_manager_registry:
        class: %pim_catalog.doctrine.smart_manager_registry.class%
        calls:
            - [addRegistry, ['@doctrine']]

    pim_catalog.doctrine.table_name_builder:
        class: %pim_catalog.doctrine.table_name_builder.class%
        arguments:
            - '@service_container'
            - '@pim_catalog.doctrine.smart_manager_registry'
