parameters:
    pim_catalog.repository.product.class:                           Pim\Bundle\CatalogBundle\Entity\Repository\MongoDBODM\ProductRepository
    pim_catalog.doctrine.completeness_generator.class:              Pim\Bundle\CatalogBundle\Doctrine\MongoDBODM\CompletenessGenerator
    pim_catalog.event_listener.mongodb.inject_orm_references.class: Pim\Bundle\CatalogBundle\EventListener\MongoDBODM\InjectORMReferencesSubscriber

services:
    pim_catalog.object_manager.product:
        alias: doctrine.odm.mongodb.document_manager

    pim_catalog.doctrine.completeness_generator:
        class: %pim_catalog.doctrine.completeness_generator.class%
        arguments:
            - '@doctrine_mongodb'
            - %pim_catalog.entity.product.class%
            - %pim_catalog.entity.product_value.class%

    pim_catalog.event_listener.mongodb.inject_orm_references:
        class: %pim_catalog.event_listener.mongodb.inject_orm_references.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_catalog.entity.attribute.class%
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }
