config:
    shim:
        jquery.form:
            deps:
                - jquery
        url:
            exports: Url
    paths:
        jquery.form:                      pimnavigation/lib/jquery-form/jquery.form
        # url-lib:                              pimnavigation/lib/url/url.min
        oro/navigation/collection:        pimnavigation/js/navigation/collection
        oro/navigation/model:             pimnavigation/js/navigation/model
