parameters:
    pim_localization.formatter.number.class:             Pim\Component\Localization\Formatter\NumberFormatter
    pim_localization.formatter.number.attribute_options: ['number_min', 'number_max']

services:
    pim_localization.formatter.number:
        class: %pim_localization.formatter.number.class%
        arguments:
            - '@security.token_storage'
            - %pim_localization.formatter.number.attribute_options%
