parameters:
    pim_filter.datasource.orm_adapter.class: Oro\Bundle\FilterBundle\Datasource\Orm\OrmFilterDatasourceAdapter

    pim_filter.ajax_choice_filter.class:  Pim\Bundle\FilterBundle\Filter\AjaxChoiceFilter

    pim_filter.product_scope_filter.class:        Pim\Bundle\FilterBundle\Filter\Product\ScopeFilter
    pim_filter.product_groups_filter.class:       Pim\Bundle\FilterBundle\Filter\Product\GroupsFilter
    pim_filter.product_family_filter.class:       Pim\Bundle\FilterBundle\Filter\Product\FamilyFilter
    pim_filter.product_completeness_filter.class: Pim\Bundle\FilterBundle\Filter\Product\CompletenessFilter
    pim_filter.product_category_filter.class:     Pim\Bundle\FilterBundle\Filter\Product\CategoryFilter

    pim_filter.product_value_string.class:     Pim\Bundle\FilterBundle\Filter\ProductValue\StringFilter
    pim_filter.product_value_choice.class:     Pim\Bundle\FilterBundle\Filter\ProductValue\ChoiceFilter
    pim_filter.product_value_number.class:     Pim\Bundle\FilterBundle\Filter\ProductValue\NumberFilter
    pim_filter.product_value_entity.class:     Pim\Bundle\FilterBundle\Filter\ProductValue\EntityFilter
    pim_filter.product_value_date.class:       Pim\Bundle\FilterBundle\Filter\ProductValue\DateRangeFilter
    pim_filter.product_value_datetime.class:   Pim\Bundle\FilterBundle\Filter\ProductValue\DateTimeRangeFilter
    pim_filter.product_value_boolean.class:    Pim\Bundle\FilterBundle\Filter\ProductValue\BooleanFilter
    pim_filter.product_value_metric.class:     Pim\Bundle\FilterBundle\Filter\ProductValue\MetricFilter
    pim_filter.product_value_price.class:      Pim\Bundle\FilterBundle\Filter\ProductValue\PriceFilter

services:
    pim_filter.ajax_choice_filter:
        class: %pim_filter.ajax_choice_filter.class%
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: ajax_choice }

    pim_filter.product_scope_filter:
        class: %pim_filter.product_scope_filter.class%
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
            - '@pim_catalog.manager.product'
            - '@pim_user.context.user'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_scope }

    pim_filter.product_category_filter:
        class: %pim_filter.product_category_filter.class%
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
            - '@pim_catalog.manager.product'
            - '@pim_catalog.manager.category'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_category }

    pim_filter.product_groups_filter:
        class: %pim_filter.product_groups_filter.class%
        arguments:
            - '@form.factory'
            - '@pim_filter.product_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_groups }

    pim_filter.product_family_filter:
        class: %pim_filter.product_family_filter.class%
        arguments:
            - '@form.factory'
            - '@pim_filter.product_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_family }

    pim_filter.product_completeness_filter:
        class: %pim_filter.product_completeness_filter.class%
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
            - '@pim_catalog.repository.product'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_completeness }

    pim_filter.product_value_string:
        class: %pim_filter.product_value_string.class%
        arguments:
            - '@form.factory'
            - '@pim_filter.product_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_value_string }

    pim_filter.product_value_choice:
        class: %pim_filter.product_value_choice.class%
        arguments:
            - '@form.factory'
            - '@pim_filter.product_utility'
            - '@pim_user.context.user'
            - %pim_catalog.entity.attribute_option.class%
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_value_choice }

    pim_filter.product_value_number:
        class: %pim_filter.product_value_number.class%
        arguments:
            - '@form.factory'
            - '@pim_filter.product_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_value_number }

    pim_filter.product_value_entity:
        class: %pim_filter.product_value_entity.class%
        arguments:
            - '@form.factory'
            - '@pim_filter.product_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_value_entity }

    pim_filter.product_value_date:
        class: %pim_filter.product_value_date.class%
        arguments:
            - '@form.factory'
            - '@pim_filter.product_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_value_date }

    pim_filter.product_value_datetime:
        class: %pim_filter.product_value_datetime.class%
        arguments:
            - '@form.factory'
            - '@pim_filter.product_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_value_datetime }

    pim_filter.product_value_boolean:
        class: %pim_filter.product_value_boolean.class%
        arguments:
            - '@form.factory'
            - '@pim_filter.product_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_value_boolean }

    pim_filter.product_value_metric:
        class: %pim_filter.product_value_metric.class%
        arguments:
            - '@form.factory'
            - '@pim_filter.product_utility'
            - '@translator'
            - '@akeneo_measure.manager'
            - '@akeneo_measure.measure_converter'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_value_metric }

    pim_filter.product_value_price:
        class: %pim_filter.product_value_price.class%
        arguments:
            - '@form.factory'
            - '@pim_filter.product_utility'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: product_value_price }
