connector:
    name: Akeneo XLSX Connector
    jobs:
        xlsx_product_import:
            title: pim_connector.jobs.xlsx_product_import.title
            type:  import
            steps:
                validation:
                    title: pim_connector.jobs.xlsx_product_import.validation.title
                    class: %pim_connector.step.validator.class%
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    title:         pim_connector.jobs.xlsx_product_import.import.title
                    services:
                        reader:    pim_connector.reader.file.xlsx_product
                        processor: pim_connector.processor.denormalization.product.flat
                        writer:    pim_connector.writer.doctrine.product
                import_associations:
                    title:         pim_connector.jobs.xlsx_product_import.import_associations.title
                    services:
                        reader:    pim_connector.reader.file.xlsx_association
                        processor: pim_connector.processor.denormalization.product_association.flat
                        writer:    pim_connector.writer.doctrine.product_association
                    parameters:
                        batch_size: 1
        xlsx_product_export:
             title: pim_connector.jobs.xlsx_product_export.title
             type:  export
             steps:
                 export:
                     title: pim_connector.jobs.xlsx_product_export.export.title
                     services:
                         reader:    pim_base_connector.reader.doctrine.product
                         processor: pim_base_connector.processor.product_to_flat_array
                         writer:    pim_connector.writer.file.xlsx_product
                     parameters:
                         batch_size: 10
        xlsx_group_export:
            title: pim_connector.jobs.xlsx_group_export.title
            type:  export
            steps:
                export:
                    title: pim_connector.jobs.xlsx_group_export.export.title
                    services:
                        reader:    pim_base_connector.reader.repository.group
                        processor: pim_connector.processor.normalization.group.flat
                        writer:    pim_connector.writer.file.xlsx_group
                    parameters:
                        batch_size: 10
        xlsx_variant_group_export:
            title: pim_connector.jobs.xlsx_variant_group_export.title
            type:  export
            steps:
                export:
                    title: pim_connector.jobs.xlsx_variant_group_export.export.title
                    services:
                        reader:    pim_base_connector.reader.repository.variant_group
                        processor: pim_connector.processor.normalization.variant_group.flat
                        writer:    pim_connector.writer.file.xlsx_variant_group
                    parameters:
                        batch_size: 10
        xlsx_group_import:
            title: pim_connector.jobs.xlsx_group_import.title
            type:  import
            steps:
                validation:
                    title: pim_connector.jobs.xlsx_group_import.validation.title
                    class: %pim_connector.step.validator.class%
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    title:         pim_connector.jobs.xlsx_group_import.import.title
                    services:
                        reader:    pim_connector.reader.file.xlsx_group
                        processor: pim_connector.processor.denormalization.group.flat
                        writer:    pim_connector.writer.doctrine.group
        xlsx_variant_group_import:
            title: pim_connector.jobs.xlsx_variant_group_import.title
            type:  import
            steps:
                validation:
                    title: pim_connector.jobs.xlsx_variant_group_import.validation.title
                    class: %pim_connector.step.validator.class%
                    services:
                        charsetValidator: pim_connector.validator.item.charset_validator
                import:
                    title:         pim_connector.jobs.csv_variant_group_import.import.title
                    services:
                        reader:    pim_connector.reader.file.xlsx_variant_group
                        processor: pim_connector.processor.denormalization.variant_group.flat
                        writer:    pim_connector.writer.doctrine.variant_group
                    parameters:
                        batchSize: 1
