parameters:
    pim_grid.datagrid.class:                     Pim\Bundle\GridBundle\Datagrid\Datagrid
    pim_grid.builder.datagrid.class:             Pim\Bundle\GridBundle\Builder\ORM\DatagridBuilder
    pim_grid.action.product_delete.class:        Pim\Bundle\GridBundle\Action\ProductDeleteAction
    pim_grid.datagrid.helper.class:              Pim\Bundle\GridBundle\Helper\DatagridHelper

    # overriden classes
    oro_grid.sorter.factory.class:               Pim\Bundle\GridBundle\Sorter\SorterFactory

services:
    pim_grid.builder.datagrid:
        class: %pim_grid.builder.datagrid.class%
        arguments:
            - '@form.factory'
            - '@event_dispatcher'
            - '@oro_security.security_facade'
            - '@oro_grid.filter.factory'
            - '@oro_grid.sorter.factory'
            - '@oro_grid.action.factory'
            - %pim_grid.datagrid.class%

    pim_grid.action.product_delete:
        class: %pim_grid.action.product_delete.class%
        tags:
            - { name: oro_grid.action.type, alias: pim_grid_action_product_delete }

    pim_grid.datagrid.helper:
        class: %pim_grid.datagrid.helper.class%
        arguments:
            - '@service_container'
